### ISSUE TITLE
token type was unexpectedly EndTag

### ISSUE THREAD

**Issue by onurcskun** [fb55/htmlparser2#1002]
```
....
<li>
  some text bla bla <}>#{/^‘|~@& bla bla
</li>
...
```

in this html, this ``` <}> ``` giving "token type was unexpectedly EndTag" error. I think if something is invalid, it should printed as text

**Comment by fb55** [comment]
This doesn't sound like an error originating from `htmlparser2`. Could you send the stack trace?

**Comment by fb55** [comment]
Happy to reopen once there is some more information!
