### ISSUE TITLE
Parsing youtube rss feed missing alot of data

### ISSUE THREAD

**Issue by whathappenedman** [fb55/htmlparser2#1017]
if you parse a youtube rss feed using

` const feed = htmlparser2.parseFeed(response.data, {xmlMode:true});`

the returned feed object omits a lot of the data. Using the Linus Tech Tips channel as an example:
https://www.youtube.com/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw

you can recreate this by pasting that url in the browser (or console.log(res)) and then comparing that to whats returned by the feed.

I couldn't find detailed docs on parseFeed so sorry if I'm just missing some options.
the readme mentioned using node-feedparser as it is better maintained but there has been not commits for over a year, so I didnt try it.

**Comment by fb55** [comment]
Hi @whathappenedman, I'm super happy accept patches that add missing entry aliases. Have a look at the `domutils` module for the code of the feed parser.

**Comment by whathappenedman** [comment]
ok will check it out. you can close this in the meant time if youd like
