### ISSUE TITLE
"value < 1" parsed error when use xmlMode:true

### ISSUE THREAD

**Issue by wutianSweet** [fb55/htmlparser2#1029]
when i use htmlparse2 parse this str, "value<10" will  be  an error open tag  in  onopentag function
```html
<wxs module="m1">
  var dateFormat = function(d,fmt){
  function formatDays(value){
  if(value<10){
  return "0"+value.toString()
  }
  return value
  }

  var date = getDate(d);
  return date.getFullYear()+"-"+formatDays(date.getMonth()+1)+"-"+formatDays(date.getDate())
  }
  module.exports.dateFormat = dateFormat;
```

**Comment by fb55** [comment]
This is unfortunately how XML tag names are handled by `htmlparser2`. If you can change your markup, you could wrap the script in a comment or a CDATA section.

Also, `value < 1` as in the title will parse correctly.
