### ISSUE TITLE
stream, pause, resume and backpressure

### ISSUE THREAD

**Issue by jeromew** [fb55/htmlparser2#103]
I have been trying to use htmlparser2 for asynchronous parsing (using pause(), resume()) and have met the following problems :

1/ Tokenizer.write does not handle backpressure

so `file.pipe(parser)` will tend to swallow all the file in memory, irrespective of where the parsing is paused or resumed

2/ using pause inside a callback

when using `parser.pause()` inside an `onopentag` callback, the parsing is correctly paused, but I had to make sure that the resume is not called in the same tick as the callback, otherwise, the `ìndex++` at the end of the parsing loop is called too late. I had a case where the `onopentag` was called 2 times.

3/ problem with `end`

when the file is piped into the parser, it `file.pipe` function ends up calling end on the parser.
when the parsing is done asynchronously, calling end while the Tokenizer is paused ends up calling `_cleanup()` which sets `this._index = 0` and `this.buffer = ""` even if the buffer is not empty.

At this stage I didn't go further as I do not know if 'asynchronous parsing' using pause/resume is something that is in the scope of htmlparser2

**Comment by qur2** [comment]
Any news on this issue? I'm streaming some file to the parser and it sometimes fails, leaving me with uncomplete strings in the result. It seems to happen when it all goes too fast. I tried buffering the file content in an array and push to the parser in a for-loop and got much more failures.

When I say failure, the parser never crashes, it just gives me uncomplete tags or values.

**Comment by fb55** [comment]
The test case in #104 looks pretty good. Will look into it when I work on this project again.

**Comment by fb55** [comment]
It's been a couple of years, I hope this has been fixed in the meantime.
