### ISSUE TITLE
how to  traversal the AST,or How to get nodes through classname？

### ISSUE THREAD

**Issue by NeuralMayu** [fb55/htmlparser2#1051]
![image](https://user-images.githubusercontent.com/82007499/146538847-e7cb24fc-1b21-495a-9f04-611853357e5b.png)

**Comment by fb55** [comment]
Have a look at https://github.com/fb55/css-select for a comprehensive querying solution, and at https://github.com/cheeriojs/cheerio for a module that builds on `css-select` and `htmlparser2`, and adds all sorts of helpers to make it easier to work with a document.
