### ISSUE TITLE
openImpliesClose logic seems to be tripped up by intervening tags

### ISSUE THREAD

**Issue by vassudanagunta** [fb55/htmlparser2#1076]
Given the following input:

``` html
<p>one <b>bold <p>two
```

htmlparser2 generates events equivalent to the following:
``` html
<p>one <b>bold <p>two</p></b></p>
```

Notice how the opening of the second `p` does not implicitly close the first. 

If you remove the intervening `<b>` tag:

``` html
<p>one bold <p>two
```

then htmlparser2 generates the correct events:
``` html
<p>one bold </p><p>two</p>
```

**Comment by fb55** [comment]
"Fixed" by #1147
