### ISSUE TITLE
Lesser than (<) in script tag causes text to be split

### ISSUE THREAD

**Issue by lachrist** [fb55/htmlparser2#112]
Hi, thanks for the awesome module! It seems the text is split when < is encountered inside script tags (as shown below). Is this the attended behaviour?

HTML
=====
\<html>
    \<script>var foo = '\<\<bar>>';\</script>
\</html>

Output
=====
TEXT>>

OPEN-TAG>>html
TEXT>>

OPEN-TAG>>script
TEXT>>
var foo = '
TEXT>>\<\<bar>>';

CLOSE-TAG>>script
TEXT>>

CLOSE-TAG>>html
TEXT>>

**Comment by mickeyckm** [comment]
I'm having the same issue as well.

**Comment by fb55** [comment]
That is intended behavior, even though I'm not a fan of it myself and this might change in the future.
