### ISSUE TITLE
HTML comments within <style> element not recognized

### ISSUE THREAD

**Issue by dfoody** [fb55/htmlparser2#1124]
All content within a `<style>` element is passed to `ontext` - however the HTML spec does support `<!-- ... -->` as a legal form of comment within style elements for older versions of HTML (see https://www.w3.org/TR/CSS21/syndata.html#comments).

It would be great if htmlparser2 would optional split style element content into `ontext` and `oncomment`.

**Comment by fb55** [comment]
`htmlparser2` trades correctness in edge-cases for speed — you might want to have a look at `parse5` for a parser that does implement all of HTML's intricacies.
