### ISSUE TITLE
ng-include tag is parsed wrong

### ISSUE THREAD

**Issue by pgilad** [fb55/htmlparser2#113]
this code:
```html
    <ng-include="index.html"></ng-include>
        <ng-pluralize count="personCount" when="{'0': 'Nobody is viewing.',
                                             'one': '1 person is viewing.',
                                             'other': '{} people are viewing.'}" />
```

is parsed wrong (see live demo). It assumes `ng-pluralize` is a child of `ng-include`. My guess is that because the open tagName has the `=index.html` and the closing doesn't - this doesn't get the closing tag correctly

**Comment by cmawhorter** [comment]
You're assigning a value to the tag name `ng-include`.   I believe ` <ng-include="index.html"></ng-include>` should be ` <ng-include src="index.html"></ng-include>`.

If not, that's yet-another-reason I hate angular.

**Comment by fb55** [comment]
Sorry for the late response. AFAIK this isn't valid HTML, won't be supported.
