### ISSUE TITLE
Use high5 as a new tokenizer

### ISSUE THREAD

**Issue by fb55** [fb55/htmlparser2#114]
Lately, a lot of tokenization-related bugs have popped up, and even though the tree-building part of high5 isn't done, its tokenizer should be ready.

This will be the `4.0.0` release of this module and will break some code – especially since a new `doctype` callback will be introduced and XML declarations (eg. `<?xml …>`) inside HTML documents will be handled as comments.

On the plus side, this means that we've got a spec compliant tokenizer, so all tokenization bugs can be pointed to the spec.

**Comment by stevenvachon** [comment]
+1

**Comment by stevenvachon** [comment]
+5

**Comment by mickeyckm** [comment]
When will this be available?

**Comment by fb55** [comment]
The tokenizer currently lacks support for positions. As soon as that's added, a new version will become available. I have no idea when I'll have the time & be motivated to do it, so I can't give a timetable or anything.

**Comment by HoldYourWaffle** [comment]
Is there any update on this?

**Comment by stevenvachon** [comment]
@HoldYourWaffle I'm not on the team, but parse5 is now the default parser.

**Comment by glen-84** [comment]
@stevenvachon The default parser for what?

**Comment by fb55** [comment]
That would be cheerio. `htmlparser2` is still shipped with the project and is used as the default parser when `xmlMode: true`

**Comment by stevenvachon** [comment]
We can probably close this?

**Comment by fb55** [comment]
Closing this as htmlparser2 should just keep its existing tokenizer.
