### ISSUE TITLE
Incorrect parsing for insane doctypes

### ISSUE THREAD

**Issue by domenic** [fb55/htmlparser2#117]
For example, the doctype at http://lists.w3.org/Archives/Public/www-dom-ts/2001Aug/att-0130/staff.xml is

```
<!DOCTYPE staff SYSTEM "staff.dtd" [
   <!ENTITY ent1 "es">
   <!ENTITY ent2 "1900 Dallas Road">
   <!ENTITY ent3 "Texas">
   <!ENTITY ent4 "<entElement domestic='Yes'>Element data</entElement><?PItarget PIdata?>">
   <!ENTITY ent5 PUBLIC "entityURI" "entityFile" NDATA notation1>
   <!ENTITY ent1 "This entity should be discarded">
   <!NOTATION notation1 PUBLIC "notation1File">
   <!NOTATION notation2 SYSTEM "notation2File">
]>
```

htmlparser2 seems to give this as a series of directives, instead of a single one.

(As for how I found this, I somehow found myself re-doing jsdom's xml support, and this is one of our test cases...)

**Comment by fb55** [comment]
Please refer to [inikulin/parse5](https://github.com/inikulin/parse5) if you need a spec-compliant parser.
