### ISSUE TITLE
the tag after custom components become the children of custom components，it shoule be the same level with custom components

### ISSUE THREAD

**Issue by Master-H** [fb55/htmlparser2#1174]
use htmlparser2 to parser html get the ast ,bu  the tag div after custom components(s-icon) become the children of custom components(s-icon)
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/19290315/165433684-e5f668b1-8422-4858-b5e4-9f641e25e511.png">

i  hope  the tag div after s-icon should be the same level with custom components （s-icon)，no the childrem of s-icon

**Comment by fb55** [comment]
Self-closing tags are ignored in HTML. htmlparser2 has an option to recognize them anyhow, but that'a opt-in.
