### ISSUE TITLE
Why package.json to add the exports field!!!

### ISSUE THREAD

**Issue by wangwei2018613** [fb55/htmlparser2#1175]
Why package.json to add the exports field, which makes the dependent package downloaded by my project unable to be imported correctly like 'lib/Parser'

**Comment by fb55** [comment]
This was done as a major release & shouldn't be an issue for upstream packages.

The parser is exported from the main export.

**Comment by wangwei2018613** [comment]
Now i use a package which depends htmlparser2, but it write  `require("htmlparser2/lib/Parser")` and  its package.json write `"htmlparser2": ">=4.1.0"`, how can i avoid webpack running error? help!

**Comment by fb55** [comment]
You can add `htmlparser2` as a dependency of your project, and npm will de-duplicate the module for you.
