### ISSUE TITLE
Bad example on front page

### ISSUE THREAD

**Issue by pkese** [fb55/htmlparser2#1184]
There's this example html in README.md

    "Xyz <script type='text/javascript'>const foo = '<<bar>>';</ script>"
                                                                ^
                                                                space

... which doesn't really parse correctly in *htmlparser2*.

If I add anything after that closing tag:

    "Xyz <script type='text/javascript'>const foo = '<<bar>>';</ script><p>something</p>"

... the parser will skip it all and attribute everything to `<script>` tag.

It's a really bad example: I've used it for testing this library and then spent lots of time figuring out why it doesn't work.

Was it supposed to work, or is it just a typo?

**Comment by fb55** [comment]
Good catch! PRs welcome 🙂

**Comment by fb55** [comment]
This was a typo — I've fixed it in https://github.com/fb55/htmlparser2/commit/e8832f00e7374f6d5b28e7938ecc9a8090c9402b. Thanks for the report!
