### ISSUE TITLE
CDATA parsing is not correct when it is not in xmlMode

### ISSUE THREAD

**Issue by yukinying** [fb55/htmlparser2#119]
It looks like the parsing code is considering CDATA block as comment block when xmlMode is not set with 
```
this.oncomment("[CDATA[" + value + "]]");
```

(as in https://github.com/fb55/htmlparser2/commit/1123da8e380761d75dfda58894c724ac8e0fec47).

This logic appears to be incorrect as "HTML bogus comment" blocks would end whenever the first `>` is seen. Thus for value like `> <div>xxx</div>`, the parsing logic will be incorrect.

**Comment by fb55** [comment]
In the context of a bogus comment, this is the right behavior. You can separately enable CDATA parsing, have a look at the options page in the wiki.

**Comment by yukinying** [comment]
I have verified with Gumbo and Parse5 such that the correct behavior for parsing input like `<![CDATA[ > <div> xxx </div>]]>` would be `<![CDATA[ >` (bogus comment) `<div>` (tag), `xxx` (text), `</div>` (tag) and `]]>` (text).

In htmlparser2 it is parsed as `<![CDATA[ > <div> xxx </div>]]>`  (bogus comment).

**Comment by fb55** [comment]
Ahh, right. I forgot it behaved this way. This will be fixed with #114.

**Comment by yukinying** [comment]
Thanks!
