### ISSUE TITLE
RSS categories support?

### ISSUE THREAD

**Issue by SachaG** [fb55/htmlparser2#120]
Does this parser support RSS categories? Or is there a whitelisted list of properties?

Here's an example feed: https://www.kimonolabs.com/api/rss/ctl9n416?apikey=okJ5sVP6RBPB261UCJQB8bG99aHOQk8O

**Comment by fb55** [comment]
I think it doesn't, and that should tell you enough. The feed parser isn't actively maintained, I've started [pointing](https://github.com/fb55/htmlparser2/blob/9e770fc21325581638c387c39fa6f30243e5ba2a/README.md#parsing-rssrdfatom-feeds) people to [danmactough/node-feedparser](https://github.com/danmactough/node-feedparser) as an alternative.

**Comment by SachaG** [comment]
Thanks, I'll check that out.
