### ISSUE TITLE
<br /> tags removed

### ISSUE THREAD

**Issue by stothek** [fb55/htmlparser2#121]
Is there a way to get the data in a tag with the `<br/ >` tags

for example 
```html
<p class="a">
hello
<br/>
world
</p>
```
turns into "helloworld" without spaces in between and it's hard to use that data.

**Comment by fb55** [comment]
I assume you've added the line breaks & just concat the `ontext` events? You might want to look for `<br>` elements in `onopentag` and add line breaks accordingly.
