### ISSUE TITLE
Is there a way to index HTML tags ?

### ISSUE THREAD

**Issue by bacloud22** [fb55/htmlparser2#1224]
I have an NLP pipeline using different libraries, so I'm looking for some generic solution to index HTML tags and replace them with white-spaces (or asterisks). This is not to confuse NLP libraries with HTML tags.

Is there a way to get the indexes ? for instance, having:

`hello world <tag>blablablabla hellooooo</tag> and so on` 

I would like some result like:

`hello world *****blablablabla hellooooo****** and so on` with an output of [13, 14]

So there are two questions:

- Is it possible to have tags masked, 
- Is it possible to have an index of the stream to be able to catch starts of any tag

(I found `onopentag` callback, but it doesn't provide an index)

Thanks a lot !!!

**Comment by fb55** [comment]
You can access the parser instance from `onopentag`, and use the `startIndex` and `endIndex` properties. One example of how to do this is https://github.com/fb55/domhandler/blob/9450578acd81f9a7a4ed65294b6db4b577e5dc21/src/index.ts#L219-L225

**Comment by bacloud22** [comment]
Thanks a lot for the support.
I would like to share something, I ended up writing a simplistic and generic solution library. You might like 😃 
[nlp-escape](https://github.com/bacloud22/nlp-escape.git)
