### ISSUE TITLE
why build scripts contain `echo '{\"type\":\"module\"}' > lib/esm/package.json`

### ISSUE THREAD

**Issue by hanzebang** [fb55/htmlparser2#1234]
Is it possible to remove it or add the `name` field in the package ?

**Comment by hanzebang** [comment]
I found this `package` when I looked it up with `pkg-up`

**Comment by fb55** [comment]
This is needed for `htmlparser2` to be available both from `require()` calls and `import` statements.

Could you elaborate your use-case for the package name? For debugging purposes, the path should be much more helpful.

**Comment by hanzebang** [comment]
We support users to configure which packages to use `babel` to compile by package name. The code is as follows:
![image](https://user-images.githubusercontent.com/46307343/178012996-5273d78f-3eb1-48fd-abf7-74d53ba53a15.png)
Now we're ready to add logic to manually verify `package.name` to handle this, like this:
![image](https://user-images.githubusercontent.com/46307343/178011502-6a3546ec-eb2f-4384-ad85-d5fb322fa907.png)

**Comment by fb55** [comment]
Very interesting use case. Thankfully, your workaround seems perfect for this use-case 👍
