### ISSUE TITLE
since htmlparser2@8 type declaration requires ts >= 4.5

### ISSUE THREAD

**Issue by olivier-martin-sf** [fb55/htmlparser2#1242]
It looks like since #1165 landed in the repo, the bundled type declarations use [mixed `exports`](https://github.com/fb55/htmlparser2/pull/1165/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R58-R61) (exporting both type and values) which was introduced in TS 4.5 AFAIK. 

I am wondering if there's an assumption that the consumer of the package runs a specific version of TS since the htmlparser2@v8.X.X release line. I tried to use that library in a project that runs under TS 4.2 and the type checker errors out as it doesn't understand the mixed exports syntax. That's the kind of error that are being thrown:

```ts
node_modules/htmlparser2/lib/index.d.ts:2:23 - error TS1005: ',' expected.

2 export { Parser, type ParserOptions };
                        ~~~~~~~~~~~~~
```

Maybe we could add a note about the minimum TS requirement or provide backward compatible type declarations (relying on [`typesVersion`](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions) and using a tool such as [`downlevel-dts`](https://www.npmjs.com/package/downlevel-dts)).

Thank you so much for your work on this awesome lib and hopefully this is useful feedback

**Comment by lehui521** [comment]
I encountered the same problem

**Comment by fb55** [comment]
I have added a note to the 8.0.0 release notes: https://github.com/fb55/htmlparser2/releases/tag/v8.0.0

The 7.x releases are still safe to use for users on older TypeScript versions, and I don't see a strong reason to maintain backwards compatibility for old TypeScript releases. Hope that makes sense!

**Comment by a-liubchenka** [comment]
@fb55 Hi
I spent lots of time today, just due to this problem.
Could you please add `perDependencies` object in `package.json` with typescript requirement?
After that I will be notified, that there is a conflict between typescript version requirements. Currently just some magic(
![image](https://user-images.githubusercontent.com/78596102/181360645-bb30054b-008f-4b88-8226-dd8d7de40969.png)

**Comment by fb55** [comment]
It is possible to use this module without TypeScript. If I added TypeScript as a peer dependency, users that don't use TypeScript would get errors. Unfortunately there is no way to specify optional peer dependencies.
