### ISSUE TITLE
err: TypeError: parseDocument is not a function

### ISSUE THREAD

**Issue by Mahoo12138** [fb55/htmlparser2#1263]
It's a stupid question, but I really cant find it out: 
```js
const { parseDocument, parseDOM } = require('htmlparser2')
```
`parseDOM` is OK, `parseDocument` is not found in the module import:
```js
const parser = require('htmlparser2')
console.log(parser)
```
```plaintext
{
  Parser: [Function: Parser],
  Tokenizer: [Function: Tokenizer],
  ElementType: {...},
  DomHandler: [Function: DomHandler],
  FeedHandler: [Getter],
  Stream: [Getter],
  WritableStream: [Getter],
  ProxyHandler: [Getter],
  DomUtils: [Getter],
  CollectingHandler: [Getter],
  DefaultHandler: [Function: DomHandler],
  RssHandler: [Getter],
  parseDOM: [Function: parseDOM],
  parseFeed: [Function: parseFeed],
  createDomStream: [Function: createDomStream],
  EVENTS: {...}
}
```

+ "version": "8.0.1"
+ node -v: v14.20.0

**Comment by fb55** [comment]
Thanks for the detailed issue! I can tell that your local version is not 8.0.1, as the `FeedHandler` was removed in that version. Clearing out dependencies and reinstalling them usually does the trick.

**Comment by Mahoo12138** [comment]
> Thanks for the detailed issue! I can tell that your local version is not 8.0.1, as the `FeedHandler` was removed in that version. Clearing out dependencies and reinstalling them usually does the trick.

Yeah! It is 8.1.0 this morning, but now it is 4.1.0  after checking it out carefully🤣. 
I saw `parseDocument` it in the type file clearly, so weird.
But it doesn't matter anymore，thank you so much, you are an amazing dev！
