### ISSUE TITLE
[Tokenizer].ontext() fired before actually text ended

### ISSUE THREAD

**Issue by Befzz** [fb55/htmlparser2#132]
Example:

    var htmlparser = require("htmlparser2");
    var parser = new htmlparser.Parser({
        ontext: function(text){
            console.log("text: ", text);
        }, onopentag: function(name, attribs){
            console.log("tag: "+name);
        },
    }, {decodeEntities: true});
    
    parser.write('<verybig');
    parser.write('tag/>');
    parser.write('<span>123');
    parser.write("456</span>");
    parser.end();

output:

    tag: verybigtag
    tag: span
    text:  123
    text:  456

IMHO output expected:

    tag: verybigtag
    tag: span
    text: 123456

it's fired at **Tokenizer.prototype._cleanup**

**Comment by fb55** [comment]
Yes, expected behavior (although not properly documented), is supposed to change in some future version (if I ever get around to it).
