### ISSUE TITLE
Export lists of elements

### ISSUE THREAD

**Issue by Pajamaman** [fb55/htmlparser2#134]
Parser.js has a lot of valuable data in it that I'd like to use, but I have to resort to copying it. Specifically, [this list of void elements](https://github.com/fb55/htmlparser2/blob/master/lib/Parser.js#L59). The list of form tags and "open implies close" might be useful as well.

It would be neato if these lived somewhere else, maybe [domelementtype](https://github.com/FB55/domelementtype), so other projects could use them.

**Comment by fb55** [comment]
Might be a good idea to expose them. For now, a simple export in `index.js` should be enough, might be moved to it's own module later on.

Something like [jadejs/void-elements](https://github.com/jadejs/void-elements) looks interesting, too, although it only includes HTML5 void elements.
