### ISSUE TITLE
onopentag attributes doesn't contain quote character or void attrs

### ISSUE THREAD

**Issue by amit777** [fb55/htmlparser2#1349]
Hi, I noticed that `onattribute` callback tells you various information like what type of quote is used, and whether the attribute is name only, vs name/value.  Is it possible to get this information about the attributes in the `onopentag` callback?

**Comment by amit777** [comment]
or if possible, could there be a parser option to enable the `attributes` callback parameter to contain this extra bit of info?

like `const parser = new htmlparser2.Parser({<callbacks>}, {attributeDetails: true})`

**Comment by fb55** [comment]
`onopentag` is a simple combination of other events (open tag name, attributes, open tag end), and quite simple to replicate. Adding options to it would reduce that simplicity. 

The good news are that you should be able to implement this yourself. Have a look at the `Parser` file to get a sense of how `onopentag` works.
