### ISSUE TITLE
Parser in xml mode considers whitespaces as attributes

### ISSUE THREAD

**Issue by CatchABus** [fb55/htmlparser2#1350]
Parser seems to consider whitespaces to be xml attributes in the following case:
```xml
<Page
  title="Hello world"
  actionBarVisible="false"/>
```
Result:
```js
{
  attributes: {
    '\n': '',
    title: 'Hello world',
    actionBarVisible: 'false'
  }
}
```
I can certainly check for `\` inside strings but it would be more comfortable if parser did it. After all, I don't see the point why `\n` gets to become an attribute name.

**Comment by fb55** [comment]
Unable to replicate this. My guess is that your input double-escaped the new lines, ie. `"\\n"`.

See https://astexplorer.net/#/gist/5cb02243cb4a8f5adc0498428532f6a9/e9611b063be935fda09392fe1a41d5cd548edf88

**Comment by CatchABus** [comment]
> Unable to replicate this. My guess is that your input double-escaped the new lines, ie. `"\\n"`.
> 
> See https://astexplorer.net/#/gist/5cb02243cb4a8f5adc0498428532f6a9/31a057d3d03fdd59dd5cdeb7151d288c360d4521

You are right, it was an input-related issue. Thank you so much for trying to replicate this!
