### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by shanhexi** [fb55/htmlparser2#1369]
ERR! (web) ./node_modules/_htmlparser2@8.0.1@htmlparser2/lib/esm/index.js 59:9
ERR! Module parse failed: Unexpected token (59:9)
ERR! You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
ERR! |     return getFeed(parseDOM(feed, options));
ERR! | }
ERR! > export * as DomUtils from "domutils";
ERR! | // Old name for DomHandler
ERR! | export { DomHandler as DefaultHandler };

**Comment by 1kvsn** [comment]
I'm facing this same issue all of a sudden.

**Comment by 1kvsn** [comment]
@fb55 Any thoughts ?

**Comment by 1kvsn** [comment]
This error doesn't appear when build is created locally. It happens in CI/CD pipeline only. I'm not directly using this package. This package is a dependency of another package I'm using https://github.com/apostrophecms/sanitize-html

**Comment by Pardeep94** [comment]
I am also facing same issue

**Comment by fb55** [comment]
As that issue states, please upgrade your webpack version or import the commonjs build.

**Comment by Lan-megumi** [comment]
I found a solution in another [issue](https://github.com/fb55/htmlparser2/issues/1237#issuecomment-1182522861). Just downgrade the package to version 7 and it will work.
```
"htmlparser2": "^7.2.0",
```
