### ISSUE TITLE
Duplicate identifier 'type'.

### ISSUE THREAD

**Issue by douzo** [fb55/htmlparser2#1379]
Error: node_modules/htmlparser2/lib/index.d.ts:2:18 - error TS2300: Duplicate identifier 'type'.

export { Parser, type ParserOptions };

I am getting the above error in my angular application. How to resolve this?

**Comment by fb55** [comment]
This is modern TypeScript syntax and requires an update to your TypeScript version. Feel free to use the previous major version of htmlparser2 if you are unable to upgrade TypeScript.
