### ISSUE TITLE
Cannot distinguish tags from text between quotes

### ISSUE THREAD

**Issue by rubenespadas** [fb55/htmlparser2#139]
HI, I have a problem with a parser because not distinguish text between quotes.

Example code:

    <script>document.write("<script>alert();</script>");</script>

I need extract: 

    document.write("<script>alert();</script>")

but get:

    document.write("<script>alert();

Demo Code:

    var htmlparser = require('htmlparser2');

    var _last_script = '';
    var _control;
    var parser = new htmlparser.Parser({
        onopentag: function(name, attribs){
            if (name === 'script') {
                if (!attribs.src) {
                    _control = true;
                }
            }
        },
        onclosetag: function(tag) {
            if(tag==='script') {
                if(_last_script != ''){
                    console.log(_last_script);
                    _last_script = '';
                }
                _control = false;
            }
        },
        ontext: function(text) {
            if(_control===true) {
                if(text!=='') {
                    _last_script += text
                }
            }
        }
    },
    {
        decodeEntities: true,
        lowerCaseTags: true,
        recognizeCDATA: true,
    });
    parser.write('<script>document.write("<script>alert();</script>");</script>');
    parser.end();

**Comment by fb55** [comment]
Sorry, but that's how browsers work.

**Comment by rubenespadas** [comment]
"<script>" this is a text
<script> this is a tag

Thanks for you response ;)

**Comment by rubenespadas** [comment]
"\<script\>" this is a text
\<script\> this is a html tag

Thanks for you response ;)
