### ISSUE TITLE
Runtime error occurs in production environment using Vite

### ISSUE THREAD

**Issue by groflaw** [fb55/htmlparser2#1502]
I am using `htmlparser2` module but I can see runtime error in production environment
It works fine in development.

![image](https://user-images.githubusercontent.com/122158150/235909454-00ce8c47-c24b-4c67-9c51-9789e36cf5bb.png)
![image](https://user-images.githubusercontent.com/122158150/235909913-987f8cab-153d-4b7f-b340-6c91668a5763.png)

This error is what I see
I found the source and I noticed that EVENTS object was `undefined` in Stream.js file
![image](https://user-images.githubusercontent.com/122158150/235910145-1db1f580-5e8f-45be-9b20-0a1185a42619.png)

It seems to be `Stream.js` file cannot import `EVENTS` object from `index.js` file

I am using Quasar framework (Vue)

**Comment by fb55** [comment]
This is a know error from an old, now unsupported, version. Please upgrade to the current release and this error should go away.
