### ISSUE TITLE
parseDocument in xmlMode，how to ignore space and crlf?

### ISSUE THREAD

**Issue by yuagonc** [fb55/htmlparser2#1532]
for example
``` js
var content = ` <root>
<node>nothing</node>
</root> `
var result = htmlparser2.parseDocument(content, {xmlMode: true})
```
result has three children becasue there is spase in start and end.
And 'root' has three children because there is crlf before \<node\> and after\</node\>

Can I only get result with one children and root node with one children?

**Comment by fb55** [comment]
There is no built-in way to do this. Your best bet is walking the DOM after parsing is done, and to remove text nodes that only include whitespace. I haven't tried it, but something like this should work:

```js
function removeWhitespaceTextNodes(node) {
  if (node.type === 'text' && /^\s*$/.test(node.data)) htmlparser2.DomUtils.removeElement(node)
  node.children?.forEach(removeWhitespaceTextNodes)
}

removeWhitespaceTextNodes(result)
```
