### ISSUE TITLE
The parser doesn't correctly parse a closing tag that is not associated to an opening tag

### ISSUE THREAD

**Issue by abarre** [fb55/htmlparser2#155]
I see that the parser break while parsing page that have a closing tag that is not associated to an opening tag.

To reproduce the problem :

```js
var htmlparser = require("htmlparser2");
var parser = new htmlparser.Parser({
    onopentag: function(name, attribs){
        console.log("onopentag", name);
    },
    onclosetag: function(tagname){
        console.log("onclosetag", tagname);
    }
}, {decodeEntities: true});
parser.write("<body></div></body>");
parser.end();
```
Output : 
```
onopentag body
onclosetag body
```
Expected output :
```
onopentag body
onclosetag div
onclosetag body
```

**Comment by fb55** [comment]
This is expected behavior. If you want to, you can manipulate the parsers internal stack and add your elements (although this is not a public interface and might break in the future).
