### ISSUE TITLE
[question] npm & versioning

### ISSUE THREAD

**Issue by LeonFedotov** [fb55/htmlparser2#161]
Hi, 
When is the next version release to npm? 
Does htmlparser2 follow semver?
thanks :)

**Comment by fb55** [comment]
> When is the next version release to npm? 

Published a new version right now.

> Does htmlparser2 follow semver?

Yes. The new version is `3.9.0`.

**Comment by LeonFedotov** [comment]
Great! Thanks :)



—
Leon
