### ISSUE TITLE
Add support for templates tags

### ISSUE THREAD

**Issue by manuel-di-iorio** [fb55/htmlparser2#162]
`<option name="test" {{ if (test == "ok") print('class="test"'); }}>`

This will compress with something like:

`<option name=test {{ if (test ="=" "ok") print('class="test"'); }}>`

Not a good behavior, it completely destroy my code.

---

Add a setting like the following, so that this can ignore all included in template tags:

    options = {
        template_start: ["<?"],
        template_end: ["?>"]
        //notice the use of arrays, in order to support multiple tags types
    }

**Comment by fb55** [comment]
Sorry, but custom templates are out of scope for this project.

**Comment by Swaagie** [comment]
@manuel-di-iorio writing a custom **parser** that understands these template directives would be the way to go.

**Comment by gucong3000** [comment]
```js
options = {
    template_start: ["<?"],
    template_end: ["?>"]
    //notice the use of arrays, in order to support multiple tags types
}
```
Does anyone know any alternative?
