### ISSUE TITLE
pTag is too strict

### ISSUE THREAD

**Issue by Marckon** [fb55/htmlparser2#1626]
it seems like many tags have been limited to not be contained each other.
https://github.com/fb55/htmlparser2/blob/24470b874800b508b06ddca249530063cbe6f759/src/Parser.ts#L22C6-L22C6
![image](https://github.com/fb55/htmlparser2/assets/24504081/4aa072ad-4726-4361-bd14-411a200519ae)
if I want to parse `<p><span>123</span><div style="display:inline">456</div></p>`, the `div` element will not be `p`'s child

**Comment by fb55** [comment]
`div` tags can be children of `p` tags; only `p` tags cannot be children of `p` tags.
