### ISSUE TITLE
Custom void elements

### ISSUE THREAD

**Issue by maltsev** [fb55/htmlparser2#164]
Is it possible to add support for custom void elements?

For example in the [PostHTML transforming tool](https://github.com/posthtml/posthtml) I'd like to use custom `include` tag to include HTML-files:

``` html
<include src="head.html"><include src="body.html">
```

Now it's parsed as:

``` html
<include src="head.html"><include src="body.html"></include></include>
```

If you'll find this improvement useful, I can implement it.

**Comment by voischev** [comment]
+1

**Comment by dannyjolie** [comment]
I'm no DOM export, but I believe that custom elements are required to have closing tags as per the specifications/working draft, and breaking this requirement would be somewhat beyond the scope of htmlparser2. Of course, I came here to request the same thing, but after doing some research I'll probably settle with making sure my custom elements are always properly closed. This is more of a browser issue than anything else: http://codepen.io/dannyjolie/pen/dMYXYJ

**Comment by luozhihua** [comment]
+1

**Comment by fb55** [comment]
Imho out of scope for this library.
