### ISSUE TITLE
[Feature request] Configurable characters for nesting attribute values

### ISSUE THREAD

**Issue by CatchABus** [fb55/htmlparser2#1668]
I was wondering if your team considers making nesting attribute values in quotes configurable.
Like decide whether to use a symbol like curly or square bracket instead of single or double quote. I know there's `htmlparser2-svelte` for curly braces (which alone has got like hundreds of thousands of downloads on its own) but if there's a configuration to support any symbol, it'd be more interesting.

**Comment by fb55** [comment]
Could you elaborate? How would these be passed down?

**Comment by fb55** [comment]
Still not sure I understand what the ask is here. Closing for now.
