### ISSUE TITLE
readable-stream has no '1.1' version at all

### ISSUE THREAD

**Issue by marguerite** [fb55/htmlparser2#168]
Hi,

If I understand correct, according to http://semver.org/:

'readable-stream':'1.1'

means 'readable-stream':'1.1.0', not 'readable-stream':'1.1.x', right?

but readable-stream's 1.1.x version starts from 1.1.7.

so actually you were requiring a version that never exists.

Marguerite

**Comment by shinima** [comment]
'1.1'  means '>=1.1.0  <1.2.0'
You can find docs here:  https://yarnpkg.com/en/docs/dependency-versions#toc-x-ranges
