### ISSUE TITLE
special tags in html attributes

### ISSUE THREAD

**Issue by aoxls** [fb55/htmlparser2#169]
HI ~~ I have som special tags in the html attributes,just like:
`<div class="<!--#echo var='myvar'-->"></div>`
it will be transformed to
`<div class="&lt;!--#echo var=&apos;myvar&apos;--&gt;"></div>`
how can i do ...

**Comment by chhschou** [comment]
Can you please show the option you used? It does not happen to me when I put the code you have through the parser.

**Comment by fb55** [comment]
Known issue — for now, passing `decodeEntities: false` as an option should fix it.
