### ISSUE TITLE
nested <a> tags  (and <button> tags)

### ISSUE THREAD

**Issue by oriSomething** [fb55/htmlparser2#170]
according to the [specs](https://www.w3.org/TR/html-markup/a.html#a-constraints):
- The interactive element `a` must not appear as `a` descendant of the `a` element.
- The interactive element `a` must not appear as `a` descendant of the `button` element.

i've built a [failing test](https://github.com/oriSomething/htmlparser2/commit/5e3f9c0b74fe2f485ba8ccb76924e7bb8bf37ee2) for only nested `<a>` tags currently

**Comment by oriSomething** [comment]
#114 related

**Comment by fb55** [comment]
Please refer to [inikulin/parse5](https://github.com/inikulin/parse5) if you need a spec-compliant parser.
