### ISSUE TITLE
Streaming to parser from http request does not trigger some events.

### ISSUE THREAD

**Issue by ajcrites** [fb55/htmlparser2#171]
This affects node v5.7.0. Other versions are untested.

I'm trying to parse webpage content by piping an http request to an htmlparser2:

``` js
'use strict';
const request = require("request");
const htmlparser = require("htmlparser2");
const parser = new htmlparser.Parser({
    ontagstart(name) { console.log(name); },
    onend() { console.log("end"); }
});

request.get("https://google.com").pipe(parser);
```

This will log `end`, but nothing else. If I change `parser` to a different stream such as `process.stdout` it prints the webpage response as expected.

I can use

```
request.get(url).on("data", data => parser.write(data)).on("end", () => parser.end());
```

I would expect `.pipe` to work in effectively the same way.

**Comment by fb55** [comment]
While the API of htmlparser2 is *close* to a writable stream, it does not implement the corresponding class. For that, there is the `WritableStream` interface. Please check if replacing `htmlparser.Parser` with `htmlparser.WritableStream` fixes this bug.

**Comment by ajcrites** [comment]
Using `WritableStream` does fix the bug :+1:

I could add a snippet in the docs about this since I don't see this behavior documented anywhere. Do you plan to implement writable stream for `Parser`?

**Comment by fb55** [comment]
When I tried this last, there was a notable performance penalty, and synchronous usage became impossible, both reasons against it. Having some documentation is a great idea, though.

**Comment by maxbrieiev** [comment]
Hi,

Replacing `htmlparser.Parser` with `htmlparser.WritableStream` didn't fix this bug for me. The code from the first comment just prints "end".

This issue is under node v5.9.1 and htmlparser2 3.9.0.

**Comment by maxbrieiev** [comment]
Sorry for confusion, "ontagstart" in the example above should read as "onopentag". It works as expected.
