### ISSUE TITLE
async function for onopentag

### ISSUE THREAD

**Issue by amit777** [fb55/htmlparser2#1710]
Is it possible to use an async function instead of regular function for `onopentag`  I need to await a promise in the function.  Do you see any possible issues with this either now or in the future?   I wonder if there will be a race condition or something where later tags could get processed before earlier ones.

**Comment by fb55** [comment]
You can use an async function, but you'll have to make sure to call `parser.pause()` as the first line of your callback (and `parser.resume()` always as the final line).
