### ISSUE TITLE
lowerCaseAttributeNames default is true without xmlMode

### ISSUE THREAD

**Issue by martypdx** [fb55/htmlparser2#1728]
I have a [fork with a test for default options](https://github.com/martypdx/htmlparser2/blob/master/src/Parser.spec.ts#L176-L206), all the attributes check out except `lowerCaseAttributeNames`. The code looked very intentional so I though I'd check if maybe the wiki docs were backwards. (though the difference in behavior with and without `xmlMode` suggests it is a bug). Given the mention of a performance penalty, seems like best to figure this out one way or another.

Docs say:

> If set to true, all attribute names will be lowercased. This has noticeable impact on speed, so it **defaults to false.**

Code says that pure default is `true`

**Comment by fb55** [comment]
Thanks for raising this! I've updated the wiki to reflect [how the code behaves.](https://github.com/fb55/htmlparser2/blob/59b3538483f123c86762bd191490ac62b23bcf53/src/Parser.ts#L239-L240)
