### ISSUE TITLE
Image File

### ISSUE THREAD

**Issue by ltc-hotspot** [fb55/htmlparser2#173]
In the Output of the HTML Parser Demo:  

`[
{
data: ' '
type: 'text'
next: {+}
prev: null
parent: null
}
{
name: '!doctype'
data: '!DOCTYPE html'
type: 'directive'
next: {+}
prev: {+}
parent: null
}
{
data: '\n'
type: 'text'
next: {+}
prev: {+}
parent: null
}
{
type: 'tag'
name: 'html'
attribs: {}
children: [+]
next: {+}
prev: {+}
parent: null
}
{
data: ' '
type: 'text'
next: null
prev: {+}
parent: null
}
]`

Where do we insert a picture image, i.e., `<picture><img alt="Lady Bug on a Leaf" srcset="./LadyBug/ladybug-973917_640_r.jpg?id=undefined&amp;cache=1454529069994" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7">
          </picture>` ?

**Comment by fb55** [comment]
Sorry, but I don't really understand the question. If you want to manipulate the DOM, try using `cheerio`, it  is much easier to use than the raw DOM.
