### ISSUE TITLE
Outputting JSON

### ISSUE THREAD

**Issue by j** [fb55/htmlparser2#175]
Is there a simple way to output HTML as JSON for use in an API?

**Comment by fb55** [comment]
Use the DOM handler, then call `JSON.stringify` :)

**Comment by j** [comment]
Well shucks, I'll dig into this again.  I was getting circular reference errors at the time.

**Comment by fb55** [comment]
Yeah, right, sorry. I think cheerio has a toJSON method that fixes this.

-- 
– Felix
