### ISSUE TITLE
Not the correct behavior with non standard attributes

### ISSUE THREAD

**Issue by mrmlnc** [fb55/htmlparser2#176]
Sorry if this question has already been asked - i have not found.

In HTML standard attributes cannot contain characters `{%` and `%}`. Unfortunately, the current version of the parser tries to treat them as attributes. For example:

```html
<select class="form-control" id="status_field" name="status">
  {% for status in statuses %}
    <option value="{{ loop.index0 }}" {% if post.status == status -%}selected{%- endif %}>{{ status }}</option>
  {% endfor %}
</select>
```

After parsing:

```js
attribs: {
  'value': '{{ loop.index0 }}',
  '{%': '',
  'if': ''
  'post.status': '=',              // <--------------- Oooops
  'status': '',
  '-%}selected{%-': '',
  'endif': '',
  '%}': ''
}
```

Thank you for your attention.

**Comment by fb55** [comment]
This will be supported as soon as it's in the HTML standard :)

**Comment by mrmlnc** [comment]
Oh well, I just thought that not necessary parse the content of the attribute :)
