### ISSUE TITLE
Using htmlparser2 in a cordova (mobile) application

### ISSUE THREAD

**Issue by rayzzed** [fb55/htmlparser2#177]
Hello,

I'm new in Javascript/mobile applications and I try to parse malformed (real life) html content.
In Java I have been able to do so using TagSoup, but I don't find any Cordova plugin to do the same.
I would like to use htmlparser2 in a mobile application based on Cordova (specifically Ionic) framework.
Is there a way to convert htmlparser2 sources to be usable as a Cordova plugin ?

It would give something like this:

```
module.controller('MyCtrl', function($scope, $cordovaHtmlParser2) {

  $scope.execute = function() {
    var parser = new $cordovaHtmlParser2.Parser({
    onopentag: function(name, attribs){
        if(name === "script" && attribs.type === "text/javascript"){
            console.log("JS! Hooray!");
        }
    },
    ontext: function(text){
        console.log("-->", text);
    },
    onclosetag: function(tagname){
        if(tagname === "script"){
            console.log("That's it?!");
        }
    }
    }, {decodeEntities: true});
    parser.write("Xyz <script type='text/javascript'>var foo = '<<bar>>';</ script>");
    parser.end();
  };
});
```

As a beginner in Javascript/Cordova/AngularJS/mobile application I perhaps sidesteps some obvious or simple way to do what I want.

Thanks for your help,

**Comment by fb55** [comment]
I sadly have no experience with Cordova :/
