### ISSUE TITLE
xmp tag is not parsed correctly

### ISSUE THREAD

**Issue by nati-elmaliach** [fb55/htmlparser2#1789]
> The [<xmp>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/xmp) HTML element renders text between the start and end tags without interpreting the HTML in between and using a monospaced font.

```
const htmlparser2 = require('htmlparser2')

const dom = htmlparser2.parseDocument("<xmp><span> im a span inside a xmp tag </span></xmp>");
const xmpTag = dom.childNodes[0];
const xmpFirstChild = xmpTag.childNodes[0];
xmpFirstChild.type; // tag
xmpFirstChild.name; // span
```

It should be parsed as text.

**Comment by fb55** [comment]
Fixed in #1790
