### ISSUE TITLE
Pass line and column number to parse callbacks

### ISSUE THREAD

**Issue by reppners** [fb55/htmlparser2#184]
Would it be possible to pass the current line and column number into the parsing callbacks?

**Comment by nickasd** [comment]
Hello and thanks for this very fast library.
Any plans on adding this feature? I would need it for building a graphical representation of a html document which allows jumping to the respective line and column in the file.

**Comment by fb55** [comment]
You get the index on the instance, which should suffice for figuring that information out yourself. No plans for adding this to the library though.

**Comment by nickasd** [comment]
Yes, I noticed that the instance has properties `start` and `end`, but when logged inside the callbacks their values always correspond to the last tag in the document (`</html>`). How is it possible to get the values for the current tag?

**Comment by iatsiuk** [comment]
@nickasd I've faced the same issue. You can check out my code for solution [code](https://github.com/iatsiuk/vuegister/blob/master/src/vuegister.js#L39).

**Comment by nickasd** [comment]
@iatsiuk Thanks for the help, but unfortunately this approach doesn't seem to work as I've mentioned in my previous comment.
