### ISSUE TITLE
Incorrect SVG elements in "void" list; other issues with SVG and MATH content in HTML

### ISSUE THREAD

**Issue by bathos** [fb55/htmlparser2#187]
Though this fortunately doesn’t effect xmlMode, I wanted to point out that the following entries in the void list that is used for HTML mode are incorrect:

```
path: true,
circle: true,
ellipse: true,
line: true,
rect: true,
use: true,
stop: true,
polyline: true,
polygon: true
```

The content specs for all of these elements do permit child nodes (specifically, animation and description elements).

Due to appearing in this list, in html mode the open tags of these elements are always treated as self-closing. This means html containing SVG cannot be safely parsed currently. (e.g. given  `<path d="..."><desc>foo</desc></path>`, which is valid, the path open tag will be considered self-closing right now and `<desc>` will end up emitting as a sibling, after it).

I believe the correct behavior could be achieved in html mode by always entering xmlMode upon hitting an SVG element and exiting it when it pops off again. This would also be sensible behavior for the math element. <del>Both SVG and MathML content is always case-sensitive XML defined by its own spec, not modified (except where overlaps occur, e.g. `<title>`) by the rules of the surrounding HTML document (https://www.w3.org/TR/html5/embedded-content-0.html#svg-0)</del> _See @carlsmith’s comment below which corrects this._

Edit: Just noticed someone actually has a PR for this already! https://github.com/fb55/htmlparser2/pull/129

But it’s been sitting there for a while :(

**Comment by carlsmith** [comment]
In case anyone ever reads this: The link is too the spec for *embedded content*, but this is about parsing *foreign elements*. 

> Both SVG and MathML content is always case-sensitive XML defined by its own spec, not
> modified (except where overlaps occur, e.g. <title>) by the rules of the surrounding HTML
> document.

This is not true. The spec requires vendors to parse inline XML differently. Tag names are case-insensitive for example.

**Comment by bathos** [comment]
@carlsmith You’re correct, thanks for updating this. When I filed this issue I was not well-versed in this. Although I got the details wrong, the issue itself (treating `<path>` as intrinsically void, etc) was real, though I haven’t used htmlparser2 in a long time and I don’t know if this is still true.

**Comment by carlsmith** [comment]
Cool. I saw it was a long time ago.

Do you know, off the top of your head, if there are any void SVG elements?

I've got `A` tags as **normal elements**, and `TITLE`, `SCRIPT`, `STYLE` and `DESC` tags as **raw text elements** (disregarding escapability). I'm treating all other SVG tags as able to be **self-closing** and **normal**, depending on whether the instance has any children or not.

**Comment by bathos** [comment]
There are none in the HTML-void sense ("implicitly self-closing"), though HTML elements may occur inside an HTML integration point inside an SVG (this is uncommon, but I mention it since technically these HTML/foreign contexts can be alternately nested).

**Comment by carlsmith** [comment]
Nice one, thank you.

> HTML elements may occur inside an HTML integration point inside an SVG

I didn't think of that, but it shouldn't be a problem. The reason I asked is that I'm working on a HTML code generator that supports inline SVG and MathML.

There's a `SpecialElement` class for comments and CDATA elements.

There's a `VoidElement`class that implements tag names and attributes, and renders like this:

    <tagname attributes>

There's a `RawTextElement`class that extends `VoidElement` with support for a raw text content string. It renders like this:

    <tagname attributes>content</tagname>

There's a `NormalElement`class that extends `VoidElement` with support for children, and renders like this:

    <tagname attributes>child for child in children</tagname>

The library does not escape anything, so escapable raw text elements reuse the `RawTextElement` logic. Template elements are syntactically indistinct from normal elements, so we reuse `NormalElement` for template elements.

For inline SVG and MathML, there is a `ForeignElement` class. When a foreign element has children, it reuses the `NormalElement` rendering logic:

    <tagname attributes>child for child in children</tagname>

If a foreign element has no children, it is rendered like this:

    <tagname attributes/>

In the library, SVG elements are all implemented as foreign elements, except for `A` tags (which are normal elements) and `TITLE`, `DESC`, `SCRIPT` and `STYLE` tags (which are raw text elements).

We have answers for the other differences between HTML and inline XML.

If you've read all of this (thank you), do you see anything wrong with the way we are classifying elements?

**Comment by bathos** [comment]
I might be missing too much context to have any helpful insights. I think a lot hinges on what the objective is. These categories don’t map directly to concepts in HTML to my knowledge, but perhaps they’re sufficient for the goals of this library.

> Template elements are syntactically indistinct from normal elements, so we reuse NormalElement for template elements.

Templates have a fair amount of nuance syntactically. Templates “take on” the properties of other parse states depending on the nature of what is seen within them. For example, a `<col>` element is discarded in contexts other than a `<colgroup>`:

```js

console.log(Object.assign(document.createElement('div'), {
  innerHTML: `<div>foo<col>bar</div>`
}).innerHTML);

// > "<div>foobar</div>"
```

However it is valid in a template that hasn’t already “switched over” to a context implied by some other tag. The template becomes _like_ a colgroup when we hit `<col>` (and as a consequence, the subsequent chardata is ignored like it would be inside `<colgroup>`):

```js
console.log(Object.assign(document.createElement('div'), {
  innerHTML: `<template>foo<col>bar</template>`
}).innerHTML);

// > "<template>foo<col></template>"
```

(Which, interestingly, means we here have a template whose members — non-whitespace chardata and a col element — could never otherwise be produced as siblings during parsing.)

I highlight that example just to illustrate that there’s a lot of nuance in HTML parsing that I don’t think this library handles. That may be by design — I think htmlparser2 doesn’t aim for compliance. [Parse5](https://github.com/inikulin/parse5) is an example of a fully compliant HTML parsing lib though which could be instructive.

> In the library, SVG elements are all implemented as foreign elements, except for A tags (which are normal elements) and TITLE, DESC, SCRIPT and STYLE tags (which are raw text elements).

I believe that when `<title>` is parsed as a foreign element, as in an SVG, it is not an RCDATA element like it would be if non-foreign. It can have any children — this is also true for `<desc>`.

> Do you see anything wrong with the way we are classifying elements?

If I understand right, the classification you’ve described is about serialization rather than parsing, right? In that case, my gut says that an approach like this is viable: serialization is much less zany than parsing. However there may be additional "types" to consider. For example, `<plaintext>` presents unique serialization challenges, and there might be special considerations needed when rendering rawtext and rcdata elements, especially `<script>`, which has unique rules at the lexical level.

_disclaimer: I am not an expert + I might be totally misunderstanding what you asked!_

**Comment by carlsmith** [comment]
I'm on my phone, but just wanted to say thank you. There's a ton of useful information in your reply. I hadn't considered that TITLE and DESC can also have children. That's a really important point that I had entirely overlooked. It's not easily fixed with the current approach either, so will require some redesign that you've allowed me to do before the code is used in production. Thanks again. I really appreciate the time and help.

**Comment by AmeliaBR** [comment]
The [spec for the HTML parser](https://html.spec.whatwg.org/multipage/parsing.html#parsing) covers a lot of the special cases. Of note: an `<svg>` or `<math>` element causes a switch to "foreign content" parsing mode (which is _not_ as strict as full XML parsing, but does recognize self-closing tags), and an SVG `<title>`, `<desc>` or `<foreignObject>` element switches back to regular HTML parsing.

Note that the HTML spec's [serialization algorithm](https://html.spec.whatwg.org/multipage/parsing.html#serialising-html-fragments) will always generate closing tags for SVG elements. Which isn't a problem for future parsing, but may be seen as messy by authors.  However, the serialization algorithm does have special rules for the [allowed XML-namespaced attributes](https://html.spec.whatwg.org/multipage/parsing.html#adjust-foreign-attributes).

**Comment by m93a** [comment]
@AmeliaBR Awesome work! Does your commit work correctly with `xmlMode`? (With `xmlMode` the parser should work exactly as it did before your change.) If it does, would you please open a PR? I would love for this fix to make it to NPM 🙂
