### ISSUE TITLE
Expose entity (en/de)coding methods

### ISSUE THREAD

**Issue by keithclark** [fb55/htmlparser2#189]
I have a need to decode a URL encoded attribute value that contains HTML entities — something like:

```html
<a href="http://www.website.com/?title=My+%26quot%3Bwebsite%26quot%3B">Link</a>
```

Decoding the URL can be done with the native `decodeURI()` methods, but I can't find a way to decode HTML entities using any of the methods exposed by htmlparser2.

The only solution I can find is to include _another_ copy of the entities module directly into my app. IMHO, it would make more sense to expose some helpers to do this. Something like `htmlparser2.Entites.decodeHtml()`

**Comment by fb55** [comment]
This module uses `entities` under the hood for entity handling.

**Comment by keithclark** [comment]
I'm aware that this module uses entities. I'm asking if you would consider exposing it's methods through the htmlparser2 interface.

**Comment by fb55** [comment]
No, having entities as a separate module should suffice IMHO.



-- 
– Felix
