### ISSUE TITLE
Truncated text on multiple write() calls

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [fb55/htmlparser2#190]
I was playing with `htmlparser2` and encountered a case where an opening tag was in a first `write()` call but the closing tag was in a second `write()` call. e.g:

```
htmlParserStream.write('<loc>AAA');
htmlParserStream.write('BBB</loc>');
```

I would've expected `ontext()` to be called once with the text `AAABBB` but it's actually called twice with the texts `AAA` and `BBB`.

I don't know if this is a bug or the expected behaviour?

It seems to be a weird behaviour because in the case of a tag like here:

```
htmlParserStream.write('<loc');
htmlParserStream.write('>AAABBB</loc>');
```

HTMLParser2 will wait for the second write and output that a `<loc>` tag was opened.

`NPM` version: `v3.7.3`
`Node.js` version: `v5.9.1`
`htmlparser2` version: `v3.9.1`

**Comment by fb55** [comment]
That is expected behavior. The parser can output text sections in several pieces.
