### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by russoedu** [fb55/htmlparser2#195]
I'm trying to scrap this URL: http://www.planalto.gov.br/ccivil_03/Constituicao/Constituicao.htm

It's working fine but all accents are broken.

"§ 4º São inelegíveis" becomes "� 4� S�o ineleg�veis"

The HTML does not have an encoding declared. Is there a way to force UTF-8?

**Comment by fb55** [comment]
The parser doesn't care about charsets. Use a library such as `iconv-lite` to get UCS2.

**Comment by russoedu** [comment]
Thanks for your answer. As you said, the problem was not in the parser. I added "encoding: 'latin1'," to my request options and it worked.
