### ISSUE TITLE
Install fail on React Native

### ISSUE THREAD

**Issue by dwilt** [fb55/htmlparser2#199]
Getting this after `npm install`ing:

![image](https://cloud.githubusercontent.com/assets/1065539/21292104/a5c89416-c4ad-11e6-951c-cbb05c92ff27.png)

**Comment by xiaoboJoin** [comment]
@dwilt ,have you fix the issue above?

**Comment by Mohamed-Abbas** [comment]
use htmlparser2-without-node-native that excludes node native modules so that you can use it in platforms like React Native

**Comment by Noitidart** [comment]
I just ran into this. Thanks @Mohamed-Abbas for that solution will try now.

**Comment by Noitidart** [comment]
Yuck non-native-node one is out of date. @fb55 is there plans on non-native-node support officially? Or in a parallel repo?
