### ISSUE TITLE
@types/htmlparser2 Is not complete

### ISSUE THREAD

**Issue by greatbody** [fb55/htmlparser2#203]
@types/htmlparser2 Is not complete
I was kind of looking into @types/htmlparser2 and found that it is not complete.

Is it possible that @fb55 can release an official version of @types/htmlparser2.

Thanks.

**Comment by fb55** [comment]
I'm not using TypeScript for anything, any official version would probably be out of sync pretty soon. FlowType on the other hand is another story, if there is some way to support both I'd be game.

**Comment by qballer** [comment]
Running in to the same issue.  I don't mind creating a PR for TS.

**Comment by fb55** [comment]
Please refer to DefinitelyTyped for this.
