### ISSUE TITLE
have column and line at all times 

### ISSUE THREAD

**Issue by qballer** [fb55/htmlparser2#205]
it would be nice to have the column, line,  _index on each step of the Tokenizer. Something like this: 
```js
function _posUpdate(c) {
  ++this._index;
  if (c === '\n') {
    this._column = 0;
    this._line += 1
  } else {
    this._column += 1;
  }
}
```
and then call it whenever position updates

**Comment by qballer** [comment]
this is probably not the right way to get because the parser can go back (- 6?)

**Comment by fb55** [comment]
@qballer That's a great reason why implementing this in user land is much easier than doing so in the tokenizer.

**Comment by qballer** [comment]
yea, i figured as much when I went further in to the code.
