### ISSUE TITLE
How can I tell which tag it is in within ontext?

### ISSUE THREAD

**Issue by elgs** [fb55/htmlparser2#208]
I'm only interested in the text in the `<title />` tag, let's say. So is there a way that tells which tag it is in within the `ontext(text)` callback. Will adding some contextual information as an additional parameter make sense? Something looks like `ontext(text, tagname)`?

I understand I probably can put an additional variable called `isInTitle` outside the whole parser, and toggle it in the `onopentag` and `onclosetag` callbacks, but I don't want to do that.

**Comment by fb55** [comment]
I would prefer to keep context tracking on the consumer side. If you need to know it, just update the current tag name on `onopentagname`.
