### ISSUE TITLE
Add new option

### ISSUE THREAD

**Issue by droooney** [fb55/htmlparser2#210]
I'm currently writing a tool that needs parsing HTML. Your library almost fits this goal except one thing: I need to differ the following cases:

```html
<div attr=""></div>
<div attr></div>
```

htmlparser2 returns for both cases
```js
{
  attribs: {
    attr: ""
  },
  ...
}
```

and it would be great if I could pass some option to the parser so that thing like
```js
{
  attribs: {
    attr: null
  },
  ...
}
```

is returned (or with `true` or `false` value, anything that's not a string).

Thanks in advance!

**Comment by fb55** [comment]
Late response: The parser returns the semantic structure of the document, which is the same for both notations. Sorry, but this is out-of-scope for this project. You are very welcome to create a fork that supports this behavior, it should be a fairly simple change.

**Comment by droooney** [comment]
It's not really convenient for me to keep up a fork, but still thank you!
