### ISSUE TITLE
Parser thinks `<[` is a valid open tag

### ISSUE THREAD

**Issue by eramdam** [fb55/htmlparser2#211]
It seems like the parser thinks `<[` is a valid tag even though it's not. I put together an example in AST Explorer so you can see for yourself https://astexplorer.net/#/gist/f086d160b24d648625050af65811ee37/a72171f906b671835458a67a7968071a09afb05c

**Comment by eramdam** [comment]
I just checked and it also happens with something like 

```html
<div>lorem ipsum (<10) dddd</div>
```

where `<10` is considered as a tag

**Comment by fb55** [comment]
Please refer to [inikulin/parse5](https://github.com/inikulin/parse5) if you need a spec-compliant parser.
