### ISSUE TITLE
Lowercase attribute names

### ISSUE THREAD

**Issue by chhschou** [fb55/htmlparser2#212]
Hi there, For some reason all attribute names are lower-cased by default which makes it difficult to work with with framework such as Angular where number of attribute names are lowerCamelCase. Any idea on how to work around this with the current parser?

**Comment by geoff-mci** [comment]
I think you need to set the lowerCaseAttributeNames option to false.
Despite the wiki saying the option defaults to false, the option appears to be xmlMode dependent.

from line 111 of Parser.js

this._lowerCaseAttributeNames = "lowerCaseAttributeNames" in this._options ?
									!!this._options.lowerCaseAttributeNames :
									!this._options.xmlMode;

**Comment by chhschou** [comment]
Thanks I set lowerCaseAttributeNames option to false and all is well.
