### ISSUE TITLE
Escaping special characters in the ontext event

### ISSUE THREAD

**Issue by agyimr** [fb55/htmlparser2#213]
I was trying to scrape a page, in which the content in the `<p>` tag was containing **&#39;**.

When I tried to log the text from the ontext method, it only shoved the text up until this character. I tried to escape it myself, but I think that the problem occurs earlier in htmlparser2, and I am unable to reach the original text. 

Does someone experienced same? Could you elaborate? :)

Thank you!

**Comment by michalhudecek** [comment]
We have similar issue parsing <title> from this URL: https://www.recode.net/2017/4/12/15274220/jeff-bezos-amazon-shareholders-letter-day-2-disagree-and-commit 

We get only the part AFTER ’ character

"This is the Jeff Bezos playbook for preventing Amazon’s demise" returns only "s demise"

**Comment by realtebo** [comment]
Same issue here.

Getting text from 

    <td>She&#39;s Gotta Have It S01e01-10</td>

I recevid as 'text' only 'She'.

I'm already using decodeEntities : true

**Comment by realtebo** [comment]
I actually work-arounded using 

    const Entities          = require('html-entities').AllHtmlEntities;

    pageContent = entities.decode(pageContent);
    parser.write(pageContent)

**Comment by fb55** [comment]
There is also a `decodeEntities` option.
