### ISSUE TITLE
Support Boolean Attributes

### ISSUE THREAD

**Issue by martypdx** [fb55/htmlparser2#215]
AFAICT Boolean and empty attributes both generate the same tokens:

```js
parser.write('<input type="checkbox" checked>')

// attributes of onopentag(name, attributes):
{ type: 'checkbox', checked: '' } 
```

Perhaps `null` should be used instead? Or a custom `Symbol`?

```js
{ type: 'checkbox', checked: null }
```

**Comment by martypdx** [comment]
hmm, looking at the [spec](http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes) more closely, it appears that an empty string value is considered equivalently to the standalone boolean attribute.

**Comment by loganvolkers** [comment]
> hmm, looking at the [spec](http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes) more closely, it appears that an empty string value is considered equivalently to the standalone boolean attribute.

W3C made some dead links 🤦. Here's the [new spec link](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes)
