### ISSUE TITLE
ontext() called several times inside the same tag

### ISSUE THREAD

**Issue by boustanihani** [fb55/htmlparser2#217]
Is it normal behaviour that `ontext()` gets called **several times inside the same tag**??

I am getting this behaviour when using the option `decodeEntities: true` and when the text includes an **Ampersand** `&`. Could this be a bug?

For example `<span>Ham & Eggs</span>` lets `ontext()` get called three times =>
- Ham
- &
- Eggs

**Comment by fb55** [comment]
Expected behavior
