### ISSUE TITLE
Is their a good way to render back HTML from a htmlparsed2 AST ?

### ISSUE THREAD

**Issue by dorian-marchal** [fb55/htmlparser2#219]
We found this package https://www.npmjs.com/package/htmlparser-to-html but it seems outdated.

**Comment by fb55** [comment]
`dom-serializer` is probably your best choice.

**Comment by dorian-marchal** [comment]
Thanks, I found `htmlparser.DomUtils.getOuterHTML(dom)` in the meantime.
