### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by tmos** [fb55/htmlparser2#223]
Hi,

I have htmlparser2 as a dependency my project, and it's causing me some troubles because of a circular dependency. It causes my lib to not be able to be packaged with rollup.js.

The ciruclar dependency is in `htmlparser2/lib/index.js` that requires `htmlparser2/lib/FeedHandlerjs` and vice versa.

The rollup issue is here https://github.com/rollup/rollup/issues/1674#issuecomment-336254281

It would be great to fix this, it would allow every project using cheerio and/or htmlparser2 to be packaged with rollup :)

Thanks a lot!

**Comment by fb55** [comment]
Happy to accept patches
