### ISSUE TITLE
Parsing with unbalanced quotes

### ISSUE THREAD

**Issue by nat4tq** [fb55/htmlparser2#224]
Hi,

Upon running htmlparser2 to identify possible injection attacks in HTML, I noticed that the HTML tags with unbalanced quotes such as "<a onmouseover='javascript:window.onerror=alert(1);>" , htmlparser2 would parse it somewhat as 

[ { data: ' Welcome, ', type: 'text' },
            { type: 'tag', name: 'arbtag' } ],

missing the "onmouseover" event. I realize that this type of HTML tag is malformed but when I try the same test case with node-htmlparser, it gets parsed with

[ { type: 'tag',
                   name: 'a',
                   attribs: 
                    { '1': '1',
                      onmouseover: 'onmouseover',
                      'javascript:window.onerror': 'alert(1);' } } ]

Would you be kind to provide some insight why the outputs differ?
Thank you.

**Comment by fb55** [comment]
Please refer to [inikulin/parse5](https://github.com/inikulin/parse5) if you need a spec-compliant parser.
