### ISSUE TITLE
incorrect parse.

### ISSUE THREAD

**Issue by GitScrum** [fb55/htmlparser2#226]
should receive by readme:
```js
1: --> Xyz
2: JS! Hooray!
3: --> var foo = '<<bar>>';
4: That's it?!
```

but I get
```js
1: "--> Xyz "
2: "JS! Hooray!"
3: "--> var foo = '"
4: "--> <"
5: "--> >';"
6: "That's it?!"
```

**Comment by fb55** [comment]
The readme's output is simplified. This is also documented in the wiki.

**Comment by GitScrum** [comment]
@fb55 why did you close the task? It is visible that the parcer does not work correctly
