### ISSUE TITLE
Parsing Markdown-in-HTML returns incorrect results

### ISSUE THREAD

**Issue by danielbrzn** [fb55/htmlparser2#227]
When I try to parse Markdown-in-HTML as follows:

`x<y` or `x<=y`

The parser will return only "x" as a text element versus the expected "`x<y`".  However, using `>` works fine and the parser detects it as a proper text element. It seems that <y is being treated as a valid tag even though it's encapsulated in backticks per Markdown syntax.

I have already fixed this in a fork by forcing anything within backticks to be rendered as text. Is there any interest for a PR with this fix?

**Comment by fb55** [comment]
This is not part of the HTML standard, so not really something this library aims to parse :/ Glad you found a fix for it!
