### ISSUE TITLE
Security flaw

### ISSUE THREAD

**Issue by viv16** [fb55/htmlparser2#231]
hi 
our code scanning tools are reporting http://cwe.mitre.org/data/definitions/80.html flaw at 

if(chunk) this.write(chunk);
--

line in .end function of Tokenizer.js. 

Can you let me know if we can do some fix to address this?

**Comment by fb55** [comment]
Closing as this does nothing to show a bug or help with reproducing it while having a pretty sensationalist title.

Please provide a test case that shows actualy fauly behavior, then I'm happy to dive in!
