### ISSUE TITLE
htmlparser2 can not handle `<img src="">` and `<custom-element/>` accurately at the same time(use xmlMode or not)

### ISSUE THREAD

**Issue by lovetingyuan** [fb55/htmlparser2#242]
when `xmlMode` is true, `<img src="">` is invalid, otherwise `<my-component/>` is invalid, however I want to handle both of them at the same time.
```html
<div id="container">
  <img src=""/>
  <img src="">
  <p></p>
  <my-component title="this tag is invalid in html5, it will wrap reset elements"/>
  <my-component></my-component>
  <p></p>
</div>
```
I hope the number of `container`'s element children could be 6, I know it goes against the standard, but could you offer an option to handle this? thanks!

**Comment by thorn0** [comment]
The parser has [the `recognizeSelfClosing` option](https://github.com/fb55/htmlparser2/wiki/Parser-options#option-recognizeselfclosing) for this use case.

**Comment by lovetingyuan** [comment]
thanks, anyway it goes against the html5 standard

**Comment by thorn0** [comment]
Still, there are use cases like yours where XMLish markup is embedded in HTML and is intended for some kind of preprocessing, not to be directly fed to the browser. And that's where the speed and flexibility of this parser shine. On the other hand, if one needs an HTML5-compliant parser, there exists parse5.
