### ISSUE TITLE
Supporting b, font tags - just need to add to the list in parser.js?

### ISSUE THREAD

**Issue by nowherenearithaca** [fb55/htmlparser2#246]
It looks like "b" and "font" tags not supported.  Is adding them as simple as adding them to parser.js?

**Comment by thorn0** [comment]
@nowherenearithaca  What exactly do you mean saying these tags aren't supported? Does something not work as expected?

**Comment by nowherenearithaca** [comment]
I came here via cheerio, for which "b" and "font" selectors weren't working - e.g., $("b"), $("font")... - it seemed that cheerio was using htmlparser2, and I didn't see that it would find them either, and was wondering if that was where the issue was (if I was even right).

**Comment by thorn0** [comment]
There is absolutely nothing special about those two tags. You're doing something wrong apparently. Consider [asking a question on StackOverflow.com](https://stackoverflow.com/help/how-to-ask).

**Comment by nowherenearithaca** [comment]
thanks - I didn't think there was anything special about them but the selectors for them weren't working - absolutely could be completely on my end.  Your response definitely helps.
