### ISSUE TITLE
Edge case for decode entities

### ISSUE THREAD

**Issue by jacktuck** [fb55/htmlparser2#247]
Hi, big fan of this project, I built a scraper on top of it just over a year ago.

Just encountered a site with (malformed?) markup. An attributed contained `&amp;quot;` which with `decodeEntities` enabled will output `&quot;`. I can see why this is the output, but ideally it would still output `"` IMO.

Should this edge case be handled? FWIW, it looks like facebook will handle the malformed string when i tested https://developers.facebook.com/tools/debug/sharing.

I can have a go at a PR if you think it should be handled.

**Comment by jacktuck** [comment]
`html-entities` doesn't handle it either, hmm...
```
var Entities = require("html-entities").AllHtmlEntities;
const entities = new Entities();
entities.decode('&amp;quot;')
// "&quot;"
```

**Comment by Dignity1988** [comment]
Fuck off . I have already unsubscribed this letters.

Пн, 24 вер. 2018 18:08 користувач Jack Tuck <notifications@github.com> пише:
