### ISSUE TITLE
Is there a way to strip the whitespace?

### ISSUE THREAD

**Issue by tclarke-scottlogic** [fb55/htmlparser2#250]
Looking at the output in the test, it produces a lot of entries of the form
```
{
  data: '\n'
  type: 'text'
  next: {+}
  prev: {+}
  parent: null
}
```
Because the HTML is in "pretty" format. Is there an option within the parser to de-prettify it before parsing?

**Comment by fb55** [comment]
The is no such feature.

**Comment by benbesuijen** [comment]
Whitespace text nodes is also giving me troubles with tables. It will be great if HTML is de-prettified before parsing. See also https://github.com/aknuds1/html-to-react/issues/79
