### ISSUE TITLE
Can not use in browser environment

### ISSUE THREAD

**Issue by yvanwangl** [fb55/htmlparser2#257]
In lib/Parser.js file:
```
require("inherits")(Parser, require("events").EventEmitter);
```
inherits module is a dependencies module, but events module is a node module, so when use htmlparser2 in
browser environment , will throw an error : `'undefined is not an object' in inherits_browser.js file`.
This is because `require("events")` is undefined.

**Comment by fb55** [comment]
You seem to be using a faulty implementation of the events module. Please make sure to have your build tool pull in the necessary dependencies.
