### ISSUE TITLE
Parser screws up inline svg

### ISSUE THREAD

**Issue by eldargab** [fb55/htmlparser2#258]
Try to parse https://gist.github.com/eldargab/3bb4ed7ddc707892a09acc92ffdb27e7 with version `3.10.0` and see that it doesn't close the first `polygon` tag. 

On other hand `3.9.2` works fine.

**Comment by fb55** [comment]
@AmeliaBR You might have more context here. Mind chiming in?

**Comment by AmeliaBR** [comment]
Well, 3.9.2 would close it because it treated _all_ `<polygon>` tags as self-closing, whether they should be or not.

But I'm not sure why the new changes would fail here. The rest of the file was parsed OK?
