### ISSUE TITLE
lowerCaseAttributeNames default value

### ISSUE THREAD

**Issue by ds009** [fb55/htmlparser2#261]
Hi, thanks for your awesome parser.
There's a misleading in the doc about [lowercaseattributenames](https://github.com/fb55/htmlparser2/wiki/Parser-options#option-lowercaseattributenames) about its default value `false` ( which is in fact lowerCaseTags default `true`).

**Comment by fb55** [comment]
Everyone is able to modify the wiki, feel free to change it to something less confusing!
