### ISSUE TITLE
Issue with parsing react directive with % sign when using cheerio

### ISSUE THREAD

**Issue by ashutoshmittal2309** [fb55/htmlparser2#262]
We have created a Webpack loader internally which uses Cheerio (which is built on top of HTMLParser2) to manipulate/inject some common HTML code within other project's index.html. 

Below is a sample React html template -

```
let source = `<html>
  <body>
     <div id="root">
        <%- reactServerSideRender %>
     <div>
  </body>
</html>`;
```

Below is the code using Cheerio.
```
import * as $ from 'cheerio';
console.log('After cheerio', source);
let $source = $.load(source);
console.log('After cheerio', $source);
```

Expected result -
```
<html>
  <body>
     <div id="root">
        <%- reactServerSideRender %>
     <div>
  </body>
</html>
```
Actual Result
  ```
<html>
  <body>
     <div id="root">
        <%- reactserversiderender="" %="">
        </%->
     <div>
  </body>
</html>
```

I did more debugging and looks it is coming from `htmlparser2` which is identifying above as a TAG. 
Below is the code from domSerializer in Cheerio where it is checking for element type.

https://github.com/cheeriojs/dom-serializer/blob/master/index.js#L82

Below are the values printed for my tag

```
element type - tag 
element name - %-
element attribute - { reactserversiderender: '', '%': '' } 
```

We should be able to identify different directives used in HTML like above for react.

**Comment by ashutoshmittal2309** [comment]
As a temporary workaround to continue using Cheerio, i had to parse the DOM using parse5 module first before calling the load function.

`const document = parse5.parse(source);
    const str = parse5.serialize(document);
    const $source = $.load(str);
`

It will be great if htmlparser also fixes this issue.

**Comment by fb55** [comment]
This is non-standard HTML, not something this module supports :/
