### ISSUE TITLE
Incorrectly parses non-closed <p>

### ISSUE THREAD

**Issue by voithos** [fb55/htmlparser2#265]
I'm using `htmlparser2` (v3.10.0) by means of `cheerio`, but the parser seems to fail with markup like the following:

```
<p>
  Blah blah
<ul>
  <li>List item</li>
</ul>
<p>Blah blah</p>
```

In the above, the first `<p>` isn't closed explicitly. It's followed by a `<ul>`, which is not allowed inside a `<p>` and should implicitly close the `<p>` per the spec: https://www.w3.org/TR/html5/syntax.html#optional-tags

Unfortunately, if I re-serialize the parsed template, I end up with something like this:

```
<p>
  Blah blah
<ul>
  <li>List item</li>
</ul>
</p><p>Blah blah</p>
```

For reference, the `cheerio` code I used to test this looks something like this:
```
const $ = cheerio.load(str, {_useHtmlParser2: true});
console.log($.html());
```

**Comment by fb55** [comment]
Feel free to add this! Modifying this object should do the trick:

https://github.com/fb55/htmlparser2/blob/1ba880b3bbf258d4e22d908a9e77503148472754/lib/Parser.js#L36-L57
