### ISSUE TITLE
Add support for attaching event listeners after Parser instantiation.

### ISSUE THREAD

**Issue by pro-src** [fb55/htmlparser2#269]
I've always preferred addEventListener/removeEventListener/on/off methods to the use of methods prefixed with `on` i.e. `onopentag` which are seemingly always all lowercase long method names. It just seems cleaner to me. Other than preference, I do think this is a feature bug.

We can achieve this now with an additional function call but it seems very hacky.

```js
const parser = new htmlparser2.Parser({
    onopentag(...args) {
        parser.emit("opentag", ...args);
    }
});

parser.on("opentag", (name, attribs) => console.log(name, attribs));
```

Since EventEmitter will always callback listeners synchronously anyway, couldn't the callbacks passed to the constructor just be removed in preference of the on/off methods?

Thanks for this awesome parser btw!

**Comment by pro-src** [comment]
I've elected to patch it for my use case.

This was the most efficient way to maintain backwards compatibility: https://gist.github.com/pro-src/2c5f7af76c7176ca2d3368f0c238370f

I'm not happy with this patch but I'll live. :smile:

**Comment by pro-src** [comment]
There's a package on npm for this now: https://www.npmjs.com/package/htmlparser2-ultron

**Comment by fb55** [comment]
Thanks for publishing this @pro-src! Closing the issue as it seems to be resolved.
