### ISSUE TITLE
Add documentation example for DomHandler and DomUtils

### ISSUE THREAD

**Issue by cbdeveloper** [fb55/htmlparser2#316]
Could somebody add an example to the README on how to get a DOM from the HTML and manipulate it with the `DomHandler` and `DomUtils`.

It's mentioned, but it has no examples. I've looked around and didn't find anything.

Thanks!

>**Get a DOM**
>The DomHandler (known as DefaultHandler in the original htmlparser module) produces a DOM (document object model) that can be manipulated using the DomUtils helper.
>The DomHandler, while still bundled with this module, was moved to its own module. Have a look at it for further information.

**Comment by fb55** [comment]
The DomHandler documentation should help: https://github.com/fb55/domhandler
