### ISSUE TITLE
Describe how to use it in the browser

### ISSUE THREAD

**Issue by cburgmer** [fb55/htmlparser2#33]
I am trying to package this library into one single distributable file that exposes the `htmlparser` name globally under the `window` object.

It seems that browserify doesn't cater to that problem but requires the main program to use the `require()` construct, too. I don't believe that this is an option for me right now.

The best solution I've found so far is

```
$ browserify -r ./lib/index > htmlparser.js
```

and then in the browser do

```
> htmlparser = require('./lib/index');
```

The next best thing I can think about is wrapping each file into a function (module style), "appending" its export to an overall `module` variable, which again sits inside a closure which is than returned and assigned to the global variable `htmlparser``.

Am I missing the point of browserify and the like?

**Comment by yvanwangl** [comment]
In lib/Parser.js file:
```
require("inherits")(Parser, require("events").EventEmitter);
```
inherits module is a dependencies module, but events module is a node module, so when use htmlparser2 in 
browser environment , will throw an error : 'undefined is not an object' in  inherits_browser.js  file.
