### ISSUE TITLE
problem with WritableStream.d.ts

### ISSUE THREAD

**Issue by tom-berend** [fb55/htmlparser2#333]
hi, I'm a newbie in TS, couldn't figure out how to fix this and give you a PR.  sorry.

When I load htmlparser2, I get an error in the d.ts file:

![problem](https://user-images.githubusercontent.com/11073753/67108622-e7f07b00-f19c-11e9-824e-63257cfaa7de.png)

I can fix it in node_modules with a redundant type declaration:

![fixed](https://user-images.githubusercontent.com/11073753/67108681-05254980-f19d-11e9-8a6e-a7ee1f50f274.png)

But I cannot figure how to modify your code to generate the d.ts file with this change.  Sorry if I am missing some basic understanding.

**Comment by gguzelj** [comment]
I just face the same error. Which version of `@types/node` are you using?
In my case, bumping from ^8 to ^12 solve the problem. I guess that `@types/node` should be a `peerDependency` instead of a `devDependency`.

**Comment by fb55** [comment]
@gguzelj Good point. Shouldn't it be both dev and peer then?

**Comment by gguzelj** [comment]
Yep, sure! I guess that the `peerDependecy` stuff it would have saved me a lot of troubleshooting time, as npm would raised warnings during install
