### ISSUE TITLE
Circular dependency reported when using rollup

### ISSUE THREAD

**Issue by scottdickerson** [fb55/htmlparser2#346]
This is with htmlparser2 version 4.0.0

Attempting to package using rollup

```(!) Circular dependency: node_modules/htmlparser2/lib/index.js -> node_modules/htmlparser2/lib/Stream.js -> node_modules/htmlparser2/lib/index.js
(!) Circular dependency: node_modules/htmlparser2/lib/index.js -> node_modules/htmlparser2/lib/Stream.js -> commonjs-proxy:/Users/scottsd/Documents/GitHub/carbon-addons-iot-react/node_modules/htmlparser2/lib/index.js -> node_modules/htmlparser2/lib/index.js
(!) Circular dependency: node_modules/htmlparser2/lib/index.js -> node_modules/htmlparser2/lib/ProxyHandler.js -> node_modules/htmlparser2/lib/index.js
(!) Circular dependency: node_modules/htmlparser2/lib/index.js -> node_modules/htmlparser2/lib/CollectingHandler.js -> node_modules/htmlparser2/lib/index.js
```

**Comment by scottdickerson** [comment]
Downstream code breaks on line 9
![image](https://user-images.githubusercontent.com/6663002/68164801-6bdb8e80-ff23-11e9-96cd-2d7bb53f613f.png)


Saying that the superCtor is undefined
![image](https://user-images.githubusercontent.com/6663002/68164830-7ac24100-ff23-11e9-9a4c-f97953367231.png)

**Comment by fb55** [comment]
This is referencing `ProxyHandler.js`, which has been removed with `4.0.0`. You are very likely using an old version and this should be fixed in current releases.
