### ISSUE TITLE
Performance optimization on the tokenizer

### ISSUE THREAD

**Issue by abarre** [fb55/htmlparser2#355]
Back in 2018, I did some investigation on the performance of htmlparser2, I realized that a big part of the consumed time what consumed by the indirection between the state and the associated method of the Tokenizer.

However, I cannot find the performance gain in the issue comment. I think that is was around 10 to 20%. 

Ref : https://github.com/fasterize/node-htmlparser/commit/12c5e65bbb70273e88b2ec09efc8d5541cf491f2#diff-00550ec11d6b5101df5a54c5fee7cc2e

Hope this help to improve the performance of this module.

**Comment by fb55** [comment]
Very interesting, will have a look at this next time I spend time on this module.

**Comment by fb55** [comment]
Just tried this in a couple of different configurations. The best I could get was still a 2x slowdown. Very curious if you can get a better result!
