### ISSUE TITLE
Parent not maintained for nested P tags.

### ISSUE THREAD

**Issue by parth3724** [fb55/htmlparser2#372]
`<p><p></p><p>hi</p></p>` & `<p><p><p>hi</p></p></p>`
both gives same dom tree.

parent is null for all dom nodes.

```js
 import htmlparser from "htmlparser2-without-node-native";

const handler = new htmlparser.DomHandler(function(err, dom) {
    //observe dom
});

const parser = new htmlparser.Parser(handler);
parser.write(rawHtml);
```

**Comment by fb55** [comment]
This is in-line with the behavior of browsers. Feel free to use `xmlMode` to opt out of this behavior.
