### ISSUE TITLE
[bug]: attributes seperated with non-breakable space not parsed properly

### ISSUE THREAD

**Issue by chimurai** [fb55/htmlparser2#413]
A non-breakable space between attributes results in incorrect parsing:

```html
<h1 tests foo="bar">My First Heading</h1>
         ^--- non-breakable space
```

current ast:

```javascript
{
  "type": "tag",
  "name": "h1",
  "attribs": {
    "tests foo": "bar"
  }
}
```

expected ast:

```javascript
{
  "type": "tag",
  "name": "h1",
  "attribs": {
    "tests": "",
    "foo": "bar"
  }
}

```

View AST online:
https://astexplorer.net/#/gist/d13142c629efe70f7b96ca3ff980890e/18c8e5c240f93bf3a45d0685bf399f398bfdfd33

non breakable space: https://en.wikipedia.org/wiki/Non-breaking_space
mac: alt + shift + space

Link to online AST with htmlparser2:

https://astexplorer.net/#/gist/d13142c629efe70f7b96ca3ff980890e/cf631a5987db518147e5d31687499701060db8d0

This issue is also present in the `posthtml-parser`, which uses `htmlparser2`:
https://github.com/posthtml/posthtml-parser/issues/40

**Comment by fb55** [comment]
This seems in-line with [what browsers do](https://jsconsole.com/?document.body.innerHTML%3D%27%3Ch1%20tests%A0foo%3D%22bar%22%3EMy%20First%20Heading%3C/h1%3E%27%3Bdocument.querySelector%28%27h1%27%29.attributes.length).

**Comment by chimurai** [comment]
Thanks for looking into to it.

Looks like non-breaking space (U+00A0) can be part of the attribute name.

https://html.spec.whatwg.org/multipage/syntax.html#attributes-2

> Attributes have a name and a value. Attribute names must consist of one or more characters other than controls, U+0020 SPACE, U+0022 ("), U+0027 ('), U+003E (>), U+002F (/), U+003D (=), and noncharacters. In the HTML syntax, attribute names, even those for foreign elements, may be written with any mix of ASCII lower and ASCII upper alphas.

CSS behaves similarly:
https://jsfiddle.net/dzpqvx6r/
