### ISSUE TITLE
 Error: Unable to resolve module `./Stream.js` from "\node_modules\htmlparser2\lib\index.js"

### ISSUE THREAD

**Issue by hirvin-faria** [fb55/htmlparser2#499]
Hello I'm trying to run a react-native project, where one of the dependencies has htmlparser2 as a dependency.

But htmlparser 2 is showing the following error:

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `./Stream.js` from `C:\Users\user\Documents\projeto\node_modules\htmlparser2\lib\index.js`: The module `./Stream.js` could not be found from 

`C:\Users\user\Documents\projetos\node_modules\htmlparser2\lib\index.js`. Indeed, none of these files exist:
* `C:\Users\user\Documents\projeto\node_modules\htmlparser2\lib\Stream.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `C:\Users\user\Documents\projeto\node_modules\htmlparser2\lib\Stream.js\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`

I checking the dependency, I noticed that it doesn't have the Stream.js file

This file appears to have been removed in recent versions of this dependency, but it appears to still be imported.

Is there any way to solve this problem?

**npx react-native info**
info Fetching system and libraries information...
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.67 GB / 7.91 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4

**Comment by jsamr** [comment]
This library explicitly targets node, see my comment here: https://github.com/archriss/react-native-render-html/issues/244#issuecomment-659360475

@fb55 If you have any insight on how this library could be compatible with other runtimes such as react-native which don't provide a stream module, that would be extremely valuable for the [archriss/react-native-render-html](https://github.com/archriss/react-native-render-html) project.

**Comment by fb55** [comment]
Should have been fixed with #517
