### ISSUE TITLE
Is there any reason why readable-stream was replaced with stream during typescript port?

### ISSUE THREAD

**Issue by jsamr** [fb55/htmlparser2#517]
@fb55 The commit 2343a8c97627e0784f3b379be37a0b72fe7346b0 replaced a `require` to `stream` with `readable-stream`, with the following rationale:

>According to the official repository of nodejs/readable-stream:
>If you want to guarantee a stable streams base, regardless of what version of Node you, or the users of your libraries are using, use readable-stream only and avoid the "stream" module in Node-core.
>Also, stream module does not exist anymore in Node 9+, breaking the library.

But the commit 759b1220c03e55a895f971deab9f1e94c30a7f61 reintroduce a direct reference to `stream`. This is hitting us: https://github.com/archriss/react-native-render-html/issues/244

**Comment by fb55** [comment]
Hi @jsamr, I feel your pain, and a future release of `htmlparser2` will move the stream to its own package. Replacing `stream` won't suffice right now, as that file also depends on `string_decoder`.

These native modules were used as they have strong stability guarantees from the NodeJS core team.

This issue made me realize that the main parser was extending `EventEmitter`, without using any functions. That has [been fixed](https://github.com/fb55/htmlparser2/commit/f30f13cdcf923490bfecc915e008c4bc703f42f9), removing one more native module.

**Comment by jsamr** [comment]
@fb55 Thank you for your understanding! Apparently, `string_decoder` is also shipped as a separate npm package by the NodeJS team, see https://github.com/nodejs/string_decoder
> string_decoder is maintained by the Streams Working Group, which oversees the development and maintenance of the Streams API within Node.js.

**Comment by fb55** [comment]
The node-specific code has been moved out of the main import, which should fix this.

**Comment by jsamr** [comment]
@fb55 Thank you so much.
