### ISSUE TITLE
Attributes/Tags of an inline SVG should be case sensitive

### ISSUE THREAD

**Issue by dgkimpton** [fb55/htmlparser2#539]
Attributes/Tags of an inline SVG are case sensitive due to SVG being an XML derived language.

With the 'lowerCaseTags' or 'lowerCaseAttributeNames' options set to true, the SVG output from htmlparser2 becomes invalid. This naturally breaks some downstream tooling (such as SVGO).

In general, I like the lowerCaseTags=true and lowerCaseAttributeNames=true options for html, but it sucks that my inlined SVG's become broken.

So I tried to create myself a fork to resolve these issues (see link at the end).

So far I've resolved the issue only for AttributeNames, but the changeset is already getting bigger than I'd originally expected. 

Before I carry on and create a monster change I'm curious if you would be likely to accept a pull request for these changes?

https://github.com/dgkimpton/htmlparser2/tree/bugfix/svg

cheers!

**Comment by fb55** [comment]
Hi @dgkimpton, thanks for the PR, this is a great starting point. Discussing here as this is a bit more fundamental: Do you have any documentation on inline SVGs being case sensitive? I just looked [at what parse5 is doing](https://astexplorer.net/#/gist/5ca1111a44b02b9e2641188db00082f6/924389739f7974df9b82a8d9870bbad6e6575021), and it seems in line with htmlparser2.

**Comment by dgkimpton** [comment]
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Introduction
"SVG elements and attributes should all be entered in the case shown here since XML is case-sensitive (unlike HTML)."

https://www.w3.org/TR/SVG11/styling.html
"Because presentation attributes are expressed as XML attributes, presentation attributes are case-sensitive and must match the exact name as specified in the DTD"

https://dev.w3.org/SVG/proposals/svg-html/svg-html-proposal.html
"SVG is an XML language by design, and therefore has certain abilities and constraints at the syntactic level that are dissimilar to those of text/html (but consistent with XHTML); therefore, to work correctly, with the full range of features, SVG must follow the syntactic rules with which it was designed, in both HTML and XHTML"

https://www.w3.org/TR/SVG2/struct.html#Namespace
When SVG is parsed as a XML, for compliance with the Namespaces in XML Recommendation [xml-names], an SVG namespace declaration must be provided so that all SVG elements are identified as belonging to the SVG namespace.
When using the HTML syntax, the namespace is provided automatically by the HTML parser.


I haven't been able to pin down a truly authoritative resource that states it unambiguously, but these were sufficient to make it seem like the right path to me.

**Comment by dgkimpton** [comment]
The link you gave to parse5 is interesting, it seems using fake attributes doesn't preserve the case, but if you use genuine ones (such as preserveAspectRatio) the case is preserved. It must be doing something extra smart under the hood.

**Comment by fb55** [comment]
It seems like parse5 corrects attributes (as well as tag names) after parsing, using [this list](https://github.com/inikulin/parse5/blob/252819607421a5741cf745bb60c404f023531b0d/packages/parse5/lib/common/foreign-content.js#L54). My current understanding is that SVG is not actually case-sensitive when embedded in HTML.

**Comment by dgkimpton** [comment]
Maintaining a list of all the case sensitive attributes (and tags) is definitely a neat way to go, although it introduces a future dependency on keeping the list up-to-date.  

As you can see here https://github.com/svg/svgo/issues/939#issuecomment-378575233 the maintainer of SVGO has the opposite opinion regarding case-sensitivity :(

It seems clear that browsers don't care about the case. But, because SVGO does care, the browser never even gets to see the attributes. My reading of the documentation is that the browsers are free not to care, but that in html the case should be preserved, so pushing to get SVGO changed seems unlikely to succeed.

Obviously I can just disable the lowercasing feature of htmlparser2 but it seems a shame to do that when only svg's get broken.

**Comment by fb55** [comment]
The current solution for this is to correct names when serializing. This [is implemented](https://github.com/cheeriojs/dom-serializer/blob/1b24211de125f9bd8ee6f58d5c451377e25d9df5/src/index.ts#L8-L11) in the `dom-serializer` module, which ships with this module (as `DomUtils.getOuterHTML`). I hope this works for you!
