### ISSUE TITLE
Make < and > tag open and close characters configurable as Parser option?

### ISSUE THREAD

**Issue by webhype** [fb55/htmlparser2#567]
I am using `htmlparser2` in kind of an off-label way to expand my own macros and tokens inside regular HTML. My custom tokens or macros have the exact same syntax as HTML tags, except that that the open and close characters are not `<` and `>`, but `[` and `]`, respectively. 

Let's say I wish to personalize a web page or outgoing message with my HTML pre-processor. I would include a pseudo HTML token `[firstname/]` and at render time, it would expand to `Bob`. This is a common, useful, and sought-after application, but tricky to implement without having a complete HTML/XML parser at hand, such as yours.

I added flexible open/close characters in 10 minutes to `htmlparser2` by simply passing two new options to the `Tokenizer` constructor, which I modified like so:

```
function Tokenizer(options, cbs) {
	this._tagOpenChar = options.tagOpenChar || "<";
	this._tagCloseChar = options.tagCloseChar || ">";
	this._state = TEXT;
	// ... other constructor stuff
}
```
This works because the global `Parser` options are passed down to the `Tokenizer` constructor.

Everywhere else that `"<"` and `">"` are hardcoded in the `Tokenizer.js` file, I replaced it with `this._tagOpenChar` and `this._tagCloseChar`, respectively.

When I construct the parser in my consuming app, I simply pass `"["` and `"]"` as new opening and closing chars like so:

```
const parser = new htmlparser2.Parser(handler, {
						xmlMode: true,
						Tokenizer: require("MyVersionOfTokenizer.js"),
						tagOpenChar: "[",
						tagCloseChar: "]",
					});
```

Bingo, `htmlparser2` delivers all my tokens to me in a neat list via its `filter` APIs, and leaves all the other HTML/XML alone. Via the `htmlparser2.DomUtils.replaceElement()` API, I can now replace the tokens with whatever expanded value I want. That's it, we now have a powerful general purpose macro expander / mail merger!

**One caveat:** When re-serializing the DOM tree back to an HTML/XML string, the less-than and greater-than signs re-appear because I did not patch the hardcoded `'<'` and `'>'` found at `dom-serializer/index.js` in the htmlparser2.DomUtils API.

So if you leave any `[` bracketed `]` tokens unchanged, or don't use `htmlparser2.DomUtils.removeElement(elem)` on all leftovers (tokens that you have no match for), they re-appear, zombie-like, as classic HTML tags surrounded by `<` and `>` in the serialized string. But if you do a thorough job expanding _all_ your tokens, or removing them if unused, this problem will never appear.

I don't know if the `DomUtils` library is under your control or not, but even just adding the flexible brackets option to `Parser` / `Tokenizer` helps tremendously. I am suggesting that you consider this powerful, quick and simple extension for your next release. It seems to work like a charm.

Thanks for a great library and thanks for considering my suggestion!

**Comment by fb55** [comment]
Hi @webhype, interesting suggestion! I am a bit afraid that making this change will open up the codebase to many more requests to make parsing just a little bit more configurable, until maintenance becomes impossible and tests cannot cover all combinations of options anymore. But don't fret, you can always just override the default tokenizer. Something like

```js
class WebHypeTokenizer extends Tokenizer {
  stateText(c) {
    if (c === '[') c = '<'
    super.stateText(c)
  }

  stateBeforeAttributeName(c) {
    if (c === ']') c = ']'
    super. stateBeforeAttributeName(c)
  }
}
```

should just do the trick.

**Comment by webhype** [comment]
Much better than making a copy of Tokenizer.js and patching it, thanks! Here's the most compact version of my [bracket] Tokenizer I could come up with:

```
const htmlparser2 = require('htmlparser2');

class MyTokenizer extends htmlparser2.Tokenizer {

	constructor(options, cbs) {
		super(options, cbs);
		this._tagOpenChar = options.tagOpenChar || "<";
		this._tagCloseChar = options.tagCloseChar || ">";
	}
	_switchChars(c) {
		if (c === this._tagOpenChar)
			c = "<"; 
		else if (c === this._tagCloseChar)
			c = ">"; 
		return c;
	}
	_stateText(c)                           { return super._stateText(this._switchChars(c)); }
	_stateBeforeTagName(c)                  { return super._stateBeforeTagName(this._switchChars(c)); }
	_stateInTagName(c)                      { return super._stateInTagName(this._switchChars(c)); }
	_stateBeforeCloseingTagName(c)          { return super._stateBeforeCloseingTagName(this._switchChars(c)); }
	_stateInCloseingTagName(c)              { return super._stateInCloseingTagName(this._switchChars(c)); }
	_stateAfterCloseingTagName(c)           { return super._stateAfterCloseingTagName(this._switchChars(c)); }
	_stateBeforeAttributeName(c)            { return super._stateBeforeAttributeName(this._switchChars(c)); }
	_stateInSelfClosingTag(c)               { return super._stateInSelfClosingTag(this._switchChars(c)); }
	_stateInAttributeName(c)                { return super._stateInAttributeName(this._switchChars(c)); }
	_stateAfterAttributeName(c)             { return super._stateAfterAttributeName(this._switchChars(c)); }
	_stateBeforeAttributeValue(c)           { return super._stateBeforeAttributeValue(this._switchChars(c)); }
	_stateInAttributeValueDoubleQuotes(c)   { return super._stateInAttributeValueDoubleQuotes(this._switchChars(c)); }
	_stateInAttributeValueSingleQuotes(c)   { return super._stateInAttributeValueSingleQuotes(this._switchChars(c)); }
	_stateInAttributeValueNoQuotes(c)       { return super._stateInAttributeValueNoQuotes(this._switchChars(c)); }
	_stateBeforeDeclaration(c)              { return super._stateBeforeDeclaration(this._switchChars(c)); }
	_stateInDeclaration(c)                  { return super._stateInDeclaration(this._switchChars(c)); }
	_stateInProcessingInstruction(c)        { return super._stateInProcessingInstruction(this._switchChars(c)); }
	_stateBeforeComment(c)                  { return super._stateBeforeComment(this._switchChars(c)); }
	_stateInComment(c)                      { return super._stateInComment(this._switchChars(c)); }
	_stateAfterComment1(c)                  { return super._stateAfterComment1(this._switchChars(c)); }
	_stateAfterComment2(c)                  { return super._stateAfterComment2(this._switchChars(c)); }
	_stateBeforeCdata6(c)                   { return super._stateBeforeCdata6(this._switchChars(c)); }
	_stateInCdata(c)                        { return super._stateInCdata(this._switchChars(c)); }
	_stateAfterCdata1(c)                    { return super._stateAfterCdata1(this._switchChars(c)); }
	_stateAfterCdata2(c)                    { return super._stateAfterCdata2(this._switchChars(c)); }
	_stateBeforeSpecial(c)                  { return super._stateBeforeSpecial(this._switchChars(c)); }
	_stateBeforeSpecialEnd(c)               { return super._stateBeforeSpecialEnd(this._switchChars(c)); }
	_stateBeforeScript5(c)                  { return super._stateBeforeScript5(this._switchChars(c)); }
	_stateAfterScript5(c)                   { return super._stateAfterScript5(this._switchChars(c)); }
	_stateBeforeStyle4(c)                   { return super._stateBeforeStyle4(this._switchChars(c)); }
	_stateAfterStyle4(c)                    { return super._stateAfterStyle4(this._switchChars(c)); }
	_stateInNamedEntity(c)                  { return super._stateInNamedEntity(this._switchChars(c)); }
	_stateInNumericEntity(c)                { return super._stateInNumericEntity(this._switchChars(c)); }
	_stateInHexEntity(c)                    { return super._stateInHexEntity(this._switchChars(c)); }
}

module.exports = MyTokenizer;
```

LOTs of functions to override. Perhaps I could still persuade you to not hardcode `"<"` or `">"` one of these days, so custom `Tokenizer`s could keep the override party to a minimum? 😛 No reply necessary if not, I understand your reasoning. Thanks again!

For those seeking to apply this to build their own tokenizer, call `htmlparser2` like so:

```
					const parser = new htmlparser2.Parser(handler, {
						xmlMode: true,
						Tokenizer: MyTokenizer,
						tagOpenChar: "[",
						tagCloseChar: "]",
					});
```
Cheers!

**Comment by webhype** [comment]
Oops there was a bug in my tokenizer class - it still parsed HTML tags on top of my bracketed custom tags. The idea was to leave any HTML alone and parse only bracketed tags `[like so/]`. The cause was that I didn't flip out naturally occurring `<` and `>` characters before parsing happens. In order to avoid tokenizing HTML completely, and only parse bracketed tokens, I also need to switch out `<` with `[` and `>` with `]` so that the original parser code becomes "blind" to HTML tags, and only ends up parsing mine.

```
const htmlparser2 = require('htmlparser2');

class MyTokenizer extends htmlparser2.Tokenizer {

	switchBoard;

	constructor(options, cbs) {
		super(options, cbs);
		const tagOpenChar = options.tagOpenChar || "<";
		const tagCloseChar = options.tagCloseChar || ">";

		this.switchBoard = {
			[tagOpenChar]: "<",	// map "[" to "<"
			[tagCloseChar]: ">",	// map "]" to ">"
			["<"]: tagOpenChar,	// map also the other way around to prevent
			[">"]: tagCloseChar,	// normal HTML tags from being tokenized
		};
	
	}

	_switchChars(c) {
		return this.switchBoard[c];
	}

	// insert all the _stateXXX() functions here as shown in my previous comment

}

module.exports = MyTokenizer;

```
