### ISSUE TITLE
[5.0.0] peerDependency warning regarding @types/node

### ISSUE THREAD

**Issue by AviVahl** [fb55/htmlparser2#590]
**Steps to reproduce:**
`mkdir htmlparser2-issue && cd htmlparser2-issue && npm init -y && npm i htmlparser2`

**Expected:**
No warnings regarding `htmlparser2`.

**Actual:**
`npm WARN htmlparser2@5.0.0 requires a peer of @types/node@^14.0.5 but none is installed. You must install peer dependencies yourself.`

**Additional info:**
This peerDependency warning is problematic for at least two types of users:
- JavaScript projects that don't use TypeScript at all, are suddenly prompted to install a `@types/*` package.
- TypeScript projects that use `@types/node@10` or `@types/node@12` to verify compatibility with a minimum node version. This is my use case.

**Suggested fix:**
Document the need for `@types/node` in the README under a TypeScript section. Remove the `peerDependency` requirement. TypeScript users are aware they need to install `@types` for external packages.

**Comment by fb55** [comment]
This was added as a direct response to #330.

@AviVahl @gguzelj @tom-berend Any suggestions how this should be handled? I'm inclined to move `@types/node` back to a dev dependency, especially as the file in question is no longer part of the main module exports.

**Comment by AviVahl** [comment]
"@types/*" packages use `"depName": "*"`, which dedupes well in npm, but creates duplicates in yarn (at lease v1; not sure about v2).

At my team, we leave it to the user to install such common @types packages, as there's no "perfect" solution.

npm@7 (newly released) currently gives an error and fails to install `htmlparser2` in a project that already has older @types/node major. one can specify --force or --legacy-peer-deps to workaround, but that's kinda annoying.
