### ISSUE TITLE
Found a parsing bug

### ISSUE THREAD

**Issue by turnmind** [fb55/htmlparser2#607]
`<a  href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23%E5%B1%B1%E4%B8%9C%E8%BF%9E%E7%BB%AD3%E5%A4%A9%E6%97%A0%E6%96%B0%E5%A2%9E%23&extparam=%23%E5%B1%B1%E4%B8%9C%E8%BF%9E%E7%BB%AD3%E5%A4%A9%E6%97%A0%E6%96%B0%E5%A2%9E%23&luicode=10000011&lfid=100103type%3D1%26amp%3Bt%3D10%26amp%3Bq%3D%23%E5%B1%B1%E4%B8%9C%E8%BF%9E%E7%BB%AD3%E5%A4%A9%E6%97%A0%E6%96%B0%E5%A2%9E%23" data-hide=""><span class="surl-text">#山东连续3天无新增#</span></a>【<a  href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%2331%E7%9C%81%E5%8C%BA%E5%B8%82%E6%96%B0%E5%A2%9E%E7%A1%AE%E8%AF%8A13%E4%BE%8B%E5%9D%87%E4%B8%BA%E5%A2%83%E5%A4%96%E8%BE%93%E5%85%A5%23&extparam=%2331%E7%9C%81%E5%8C%BA%E5%B8%82%E6%96%B0%E5%A2%9E%E7%A1%AE%E8%AF%8A13%E4%BE%8B%E5%9D%87%E4%B8%BA%E5%A2%83%E5%A4%96%E8%BE%93%E5%85%A5%23&luicode=10000011&lfid=100103type%3D1%26amp%3Bt%3D10%26amp%3Bq%3D%23%E5%B1%B1%E4%B8%9C%E8%BF%9E%E7%BB%AD3%E5%A4%A9%E6%97%A0%E6%96%B0%E5%A2%9E%23" data-hide=""><span class="surl-text">#31省区市新增确诊13例均为境外输入#</span></a>】10月17日0—24时，31个省（自治区、直辖市）和新疆生产建设兵团报告新增确诊病例13例，均为境外输入病例（上海5例，广东4例，陕西2例，天津1例，四川1例）；无新增死亡病例；新增疑似病例1例，为境外输入病例（在上海）。<br />当日新增治愈出院 ...<a href="/status/4561290573909535">全文</a>`
**After parsing**
span data
#山东连续3天无新增#【
**It should be like this**
#山东连续3天无新增#

**Comment by dench201-cool** [comment]
> `<a href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%23%E5%B1%B1%E4%B8%9C%E8%BF%9E%E7%BB%AD3%E5%A4%A9%E6%97%A0%E6%96%B0%E5%A2%9E%23&extparam=%23%E5%B1%B1%E4%B8%9C%E8%BF%9E%E7%BB%AD3%E5%A4%A9%E6%97%A0%E6%96%B0%E5%A2%9E%23&luicode=10000011&lfid=100103type%3D1%26amp%3Bt%3D10%26amp%3Bq%3D%23%E5%B1%B1%E4%B8%9C%E8%BF%9E%E7%BB%AD3%E5%A4%A9%E6%97%A0%E6%96%B0%E5%A2%9E%23" data-hide=""><span class="surl-text">#山东连续3天无新增#</span></a>【<a href="https://m.weibo.cn/search?containerid=231522type%3D1%26t%3D10%26q%3D%2331%E7%9C%81%E5%8C%BA%E5%B8%82%E6%96%B0%E5%A2%9E%E7%A1%AE%E8%AF%8A13%E4%BE%8B%E5%9D%87%E4%B8%BA%E5%A2%83%E5%A4%96%E8%BE%93%E5%85%A5%23&extparam=%2331%E7%9C%81%E5%8C%BA%E5%B8%82%E6%96%B0%E5%A2%9E%E7%A1%AE%E8%AF%8A13%E4%BE%8B%E5%9D%87%E4%B8%BA%E5%A2%83%E5%A4%96%E8%BE%93%E5%85%A5%23&luicode=10000011&lfid=100103type%3D1%26amp%3Bt%3D10%26amp%3Bq%3D%23%E5%B1%B1%E4%B8%9C%E8%BF%9E%E7%BB%AD3%E5%A4%A9%E6%97%A0%E6%96%B0%E5%A2%9E%23" data-hide=""><span class="surl-text">#31省区市新增确诊13例均为境外输入#</span></a>】10月17日0—24时，31个省（自治区、直辖市）和新疆生产建设兵团报告新增确诊病例13例，均为境外输入病例（上海5例，广东4例，陕西2例，天津1例，四川1例）；无新增死亡病例；新增疑似病例1例，为境外输入病例（在上海）。<br />当日新增治愈出院 ...<a href="/status/4561290573909535">全文</a>`
> **After parsing**
> span data
> #山东连续3天无新增#【
> **It should be like this**
> #山东连续3天无新增#

**Comment by fb55** [comment]
I am not able to replicate this locally, but can see this issue on AST Explorer.

@turnmind Did you experience this locally? Otherwise it might be an AST Explorer issue, similar to https://github.com/fb55/domhandler/issues/273

**Comment by fb55** [comment]
Closing due to a lack of context. Happy to reopen should more information be provided.
