### ISSUE TITLE
Converting html entity name

### ISSUE THREAD

**Issue by Scrum** [fb55/htmlparser2#630]
Hi i am trying a code like this and it converts html entity name into symbols

```js
const htmlparser2 = require("htmlparser2");
const parser = new htmlparser2.Parser({
    ontext(text) {
        console.log("-->", text);
    }
});
parser.write("&zwnj;&nbsp;&copy;");
parser.end();
```

**response**
```
"-->"
"‌"
"-->"
" "
"-->"
"Â©"
```
This is bug ? Or where is there an option to disable it?

**Comment by fb55** [comment]
Thanks for flagging. Looks like you want to set `decodeEntities` to `false`. I've updated the wiki.
