### ISSUE TITLE
Newlines in <script> tag content that contains strings that look like HTML tags

### ISSUE THREAD

**Issue by Zer0Divis0r** [fb55/htmlparser2#635]
HTML tags become prepended with newline even if they are inside <script> tags.
As a result, `ontext` parameter of parsing of line like:
```
<script>
$('<p>Hello</p><hr><br>Good bye');
</script>
```
gives:
```
$('
<p>Hello
</p>
<div>fff
</div>
<hr>
<br>Good bye');

```

**Comment by Zer0Divis0r** [comment]
Actually, even example code from the documentation gives me a different result.

Docs say the result would be:
```
--> Xyz
JS! Hooray!
--> var foo = '<<bar>>';
That's it?!
```
I am getting:
```
--> Xyz 
JS! Hooray!
--> var foo = '
--> <
--> <bar>>';
That's it?!
```

What could be the problem?

**Comment by fb55** [comment]
Text is emitted in multiple fragments, whenever parsing might switch to a different mode. You will have to combine text nodes in your code. The same applies to comment data.

**Comment by fb55** [comment]
Assuming this is resolved, please let me know if it isn't.

**Comment by Zer0Divis0r** [comment]
But don't you think that the documentation should reflect what the code _actually_ does? Or at least mention that the text has to be combined?

**Comment by fb55** [comment]
That's what the _simplified_ in the read me is supposed to do. I'm not particularly happy with this, feel free to suggest alternative phrasing.
