### ISSUE TITLE
Very disturbing: reluctant to throw, wants to eat it all

### ISSUE THREAD

**Issue by jsamr** [fb55/htmlparser2#641]
I was trying to test all branches of my source code, so I tried to fail the Parser.
The defined function is a promise-wrapper over Parser + DomHandler API:

```js
import { DomHandler, Node } from "domhandler";
import { Parser } from "../Parser";

function parseAsync(html: string) {
    return new Promise<Node[]>((resolve, reject) => {
        const parser = new Parser(
            new DomHandler((error, documentTree) => {
                if (error) {
                    reject(error);
                } else {
                    resolve(documentTree);
                }
            })
        );
        parser.write(html);
        parser.end();
    });
}
```
The thing is, I can't seem to make it fail! I even tried to pass an object, and it resolved to a one-item text node list with data set to "[object Object]".  Do you know any circumstances where the `onerror` callback will be called? I've heard this parser is forgiving, but I'd like him to say no, at least once... If it is really that forgiving, I might end up removing the reject(error) line (btw, I'm joking with the tone, this library is fantastic, thank you!).

**Comment by fb55** [comment]
The main error is writing to the parser after calling `.end()`.

**Comment by fb55** [comment]
You can also use the library's `parseDOM` function for the same behavior, synchronously.

**Comment by jsamr** [comment]
@fb55 Copy that, thank you!
