### ISSUE TITLE
Advice for using in deno?

### ISSUE THREAD

**Issue by stereosteve** [fb55/htmlparser2#706]
Was interested in using this package (and friends) in deno.  I tried using 3 of the ES Modules packaging services:

```ts
// import { parseDocument } from "https://jspm.dev/htmlparser2";
// works, but no typing

import { parseDocument } from "https://esm.sh/htmlparser2?no-check";
// works if you add ?no-check but no typing
// otherwise:
//   error: TS2748 [ERROR]: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

// import { parseDocument } from "https://cdn.skypack.dev/htmlparser2";
// doesn't work
// error: An unsupported media type was attempted to be imported as a module.
//   Specifier: https://cdn.skypack.dev/-/entities@v2.2.0-zW9Q7GAB8ju1OuIEz905/dist=es2020,mode=raw/lib/maps/legacy.json
//   MediaType: Json

const dom = parseDocument("<div>Hello <p>there</p></div>");
console.log(dom);
```

And also found [this repo](https://github.com/tbjgolden/deno-htmlparser2/blob/master/codemod.md) which also pulls together the various pieces, tho outdated versions of them.

Some of the pain seems to come from the round trip of the various build steps involved.  Since htmlparser2 and friends are now all written in TS, it seems like this round trip could be avoided, though I don't know exactly what all is involved.

Anyway I wanted to ask if you have thought about publishing "deno friendly" versions of these packages, or have any advice about using in deno?

**Comment by fb55** [comment]
Seems like esm.sh is having the issue reported in https://github.com/fb55/domelementtype/issues/16, while Skypack is failing to load a JSON file. If you have any ideas for https://github.com/fb55/domelementtype/issues/16, that seems like it might move the needle quite a bit.

**Comment by fb55** [comment]
https://github.com/fb55/domelementtype/issues/16 is fixed now, and it seems like all of the loaders work! Closing this for now, please let me know if this is still an issue!
