### ISSUE TITLE
Browserify bundle is over 300 KB

### ISSUE THREAD

**Issue by christophercliff** [fb55/htmlparser2#71]
I realize this may not be a goal of the project, but the file size is probably too big for the browser.

Maybe there's a large `require` somewhere that could be swapped out easily.

**Comment by davidmccabe** [comment]
@fb55 The `high5` repo that you linked to has been archived, so I assume that project is abandoned. Do you know of an HTML parser made to run in the browser? Thanks.

**Comment by fb55** [comment]
Yeah - high5 was the wrong approach to continuing this project. htmlparser2 is alive and well. The native dependencies were removed from htmlparser2 a while ago, please let me know if you encounter any issues running htmlparser2 in browsers.
