### ISSUE TITLE
Allow to identify explicitly empty attribute

### ISSUE THREAD

**Issue by AndrewMayorov** [fb55/htmlparser2#721]
Now these two cases produce the same values in `onattribute` and `onopentag` callbacks. In both cases we get empty string. Is it possible to somehow tell first case from second? It is useful for parsing and re-emitting Angular templates for example.
```
<element attr />
<element attr="" />
```

**Comment by AndrewMayorov** [comment]
I see that there are already a few declined requests for that. And also understand that this is a breaking change, so perhaps this could be only implemented with introduction of a special configuration switch. 

So perhaps the we should start with the question if there is a strong opinion against this feature?

**Comment by fb55** [comment]
This is actually supported! The `onattribute` event does expose the quotes as its third parameter. It will have the quote character (`"` or `'`), or `null` for no quotes, or `undefined` for no value (no `=` after the attribute).


This won't be part of the DOM by default, but you can extend domhandler easily to add this to the current DOM node (probably as a separate object).
