### ISSUE TITLE
No error when wrong tag is closed

### ISSUE THREAD

**Issue by AndrewMayorov** [fb55/htmlparser2#736]
I just discovered that the following HTML gets parsed incorrectly:
```
<outer>
    <span>Before</span>
    <inner>
        Inner
    </inner-wrong>
    <span>After</span>
</outer>
```
Here I would expect to have some sort of error at `</inner-wrong>` line. Or at least to get `onclosetag` event and check the elements stack myself. But in fact this line just gets ignored. So the second span goes inside the `<inner>` element. And `<inner>` element itself is auto-closed at `</outer>` line.

Having this problem in version 6.0.0. Honestly, don't know if it was like this before, because I did not expected that to fail, so didn't test.

**Comment by fb55** [comment]
Hi @AndrewMayorov, this has always been the case. You could hook into the tokenizer directly to get events for closing tags that didn't have a corresponding opening tag.

**Comment by AndrewMayorov** [comment]
@fb55, found one problem along the way (so far): Parser Callbacks interface is not exported. But I see that in the latest sources you already fixed that. Do you plan to release it soon?

**Comment by fb55** [comment]
There were no code changes after the `6.0.0` release. Are you using the latest version?

**Comment by AndrewMayorov** [comment]
Yes. And I understood my mistake. In the latest sources it's also not fixed.

`Tokenizer` constructor refers to `Callbacks` interface, which is not exported. So when I try to subclass the tokenizer to hook into it, I cannot properly type the parameter.

**Comment by fb55** [comment]
Super happy to accept a PR that exports it!

**Comment by vassudanagunta** [comment]
@xorets did you ever implement the custom handler? What do you think about #845?

**Comment by xorets** [comment]
@vassudanagunta, yes, solved the problem with extending the standard `Tokenizer`. You can find my variant here: https://github.com/xorets/tshtml/blob/main/tshtml/src/parser.ts#L13

The way it's extended looks strange. It's in no way a proper OO approach, but this is how I was able to make it working. Don't know if I just didn't see the better way, or this is the way. Anyway, you should be able to solve your task the same way.
