### ISSUE TITLE
Support for custom self-closing tags?

### ISSUE THREAD

**Issue by gilbert** [fb55/htmlparser2#767]
Hi, would it be possible to provide a way for htmparser2 to expose an option to allow custom tags that auto self close? In other words, an option to extend [this record](https://github.com/fb55/htmlparser2/blob/1ce1d3bb7e3a1a70ce61f5bef5251f77ff3dbe37/src/Parser.ts#L15)? I'm working on an html-based framework and would like to allow users to write a `<page>` tag without worrying about whether they need to write `</page>` or end with `/>`.

Thanks for the great library.

**Comment by gilbert** [comment]
Ok, so I pointed to the wrong thing. Turns out I need to extend [voidElements](https://github.com/fb55/htmlparser2/blob/1ce1d3bb7e3a1a70ce61f5bef5251f77ff3dbe37/src/Parser.ts#L65) instead.

[Here's the commit I'm using to do this](https://github.com/LancerStudio/htmlparser2/commit/2b5fb9bfa16c85de9871b398e0810a3b0512ee98). If you'd like a PR, let me know. Or feel free to copy in the code yourself, no attribution needed.

**Comment by floratmin** [comment]
I am also trying to parse .svelte files which have custom self-closing tags and on top there can be props in the form `prop={javascript code}` or `prop="{javascript code}"`. When the first one comes as last prop and there is no space between the slash of the self closing tag, than the slash is added to the property like `{javascript code}/` and there is no possibility to close the tag. Actually it would be sufficient for me to have access to the whole tag as a string on `onopentag`.

**Comment by floratmin** [comment]
@fb55 thank you to make me aware of this library, but same problem there. I reported it there.

**Comment by gilbert** [comment]
@fb55 Thats sounds great to me!
