### ISSUE TITLE
many missing dependencies

### ISSUE THREAD

**Issue by electrovir** [fb55/htmlparser2#775]
I tried using this package in a Node.js project and got the following error:

```
Cannot find module 'cheerio'
```

Okay, so I installed `cheerio`. Then I got the next error:

```
describe is not defined
```

Okay... so I installed `jest` (which is gigantic btw). Then I got the next error:

```
Cannot find module '@sinonjs/referee-sinon'
```

That was too much for me so I stopped there.

**Comment by fb55** [comment]
A `npm install` doesn't do the job?

**Comment by fb55** [comment]
None of these dependencies should be necessary to use this module btw, they are used only for htmlparser2's own unit tests.

**Comment by electrovir** [comment]
Ah, my bad. I figured out what was going wrong. I had a glob for grabbing and running `**/*.test.js` files and it wasn't ignoring `node_modules`. Looks like tests are shipped with this package on npm. I updated my glob and now it's all good.

Sorry for the trouble and thanks for the response!

**Comment by fb55** [comment]
I [cannot see](https://unpkg.com/browse/htmlparser2@6.0.1/) any test files in the shipped bundle. I have the suspicion that this is coming from some sub-dependency; do you still have the path of the files?

**Comment by electrovir** [comment]
Ah, right, I didn't look that closely at it. It is coming from here: `node_modules/dom-serializer/lib/index.test.js` That is the only `.test.js` file in `node_modules` with my current dependency list (which includes `htmlparser2`).

**Comment by fb55** [comment]
Fixed in https://github.com/cheeriojs/dom-serializer/commit/4cc67c74f7279352a721ae636c45af2ff262e4e1!

**Comment by electrovir** [comment]
Nice! I'm glad this issue could still be of some help! 😄
