### ISSUE TITLE
svg parsing

### ISSUE THREAD

**Issue by Swaagie** [fb55/htmlparser2#79]
referencing https://github.com/fb55/htmlparser2/pull/75 as some basic svg shapes were already added as inline, but the list is rather incomplete. Inline svg is probably going to be a lot more common with increasing browser support. At least `polyline` and `polygon` are missing, but there might be more. As @fb55 mentioned there are several other issues with changing the inline list, perhaps we can discuss this issue here and come to a more complete fix.

**Comment by fb55** [comment]
Please refer to [inikulin/parse5](https://github.com/inikulin/parse5) if you need a spec-compliant parser.
