### ISSUE TITLE
Add option to ignore tags

### ISSUE THREAD

**Issue by jsamr** [fb55/htmlparser2#801]
Would be nice to be able to ignore specific tags without requiring a tree traversal. Perhaps `Handler.onopentag` signature could allow to return `true` in which case the element would not be added to the tree?

**Comment by fb55** [comment]
You are able to provide a custom handler, which could filter out tags:

If you want to ignore the tag, and immediately insert its contents:

```js
class FilteringHandler extends DomHandler {
  onopentag(name, attribs) {
    if (name !== 'section') super.onopentag(name, attribs)
  }

  onopentag(name, attribs) {
    if (name !== 'section') super.onopentag(name, attribs)
  }

  onclosetag(name) {
    if (name !== 'section') super.onclosetag(name)
  }
}
```

If you want to remove or otherwise modify a tag as soon as it has been written, you should have a look at the `cornet` module.
