### ISSUE TITLE
Unnecessary TextNodes

### ISSUE THREAD

**Issue by wizjamin** [fb55/htmlparser2#837]
When parsing html
e.g 
```
<body>
     <p></p>
     <p></p>
</body>
```

I expect the dom object to have a body element with 2 children but instead i'm getting 3 extra textNodes I.e
```
[body]
     [textNode]
     [p]
     [textNode]
     [p]
     [textNode]
[/body]

```
Is there a way to easily fix this?
Thanks

**Comment by fb55** [comment]
The text nodes are for the whitespace between your nodes, which does have a semantic meaning in some cases. You could use `cheerio` to get a much simpler interface to interact with.
