### ISSUE TITLE
Any ways I can use htmlparser2 as a standalone script in a non-node environment ?

### ISSUE THREAD

**Issue by gkpo** [fb55/htmlparser2#839]
I'm looking for a way to use htmlparser2 in a non-node env. The environment can run js, declare functions and everything. I just can't make an import or require.
The ideal would be if I could wrap htmlparser2 into a single js file or something. Maybe it would create a global variable called 'htmlparser2'. That I could then call to create a new parser instance.
Any ideas how I could do this ?

**Comment by fb55** [comment]
This is very much possible! You will need to use a bundler, such as Webpack, to bundle up everything into a single JS file without any imports.

**Comment by fb55** [comment]
Skypack might also come in handy: https://www.skypack.dev
