### ISSUE TITLE
RFE: parser option to report ignored and inserted tags

### ISSUE THREAD

**Issue by vassudanagunta** [fb55/htmlparser2#845]
I understand why `htmlparser2` gracefully handles malformed HTML, automatically closing unclosed tags  and skipping extraneous close tags: because that is how browsers handle it and it is even part of the HTML spec.

But there are use cases where one needs to know that these things are happening. For example I am using the parser as a tool that does some validation and reformatting. I want to know that a tag wasn't closed, or that a close was inserted because it was missing. 

Would you be open to an option wherein those events are reported? 

For example, there could be a `strict mode`, which would report these events via `onerror` or a separate handler callback, OR as follows:
  -  in `strict mode`, `onclosetag` is called for all closing tags, including skipped ones.
  -  when `onclosetag` is called, it includes an additional arg indicating if the tag was skipped or inserted.

This would be backward compatible, and would not affect performance when disabled.

**Comment by vassudanagunta** [comment]
Also, thought `xmlMode` would behave strictly, but it doesn't.  Unlike HTML, XML should always be parsed strictly.

**Comment by fb55** [comment]
Thanks for the proposal! This was implemented in #930: Both `onopentag` and `onclosetag` now have an `isImplied` flag, which indicates if the tag was created implicitly.

About a strict mode: I am not sure how much value this would provide. `htmlparser2` supports a subset of HTML and XML, without following a spec, and any error reported could be up for debate.

**Comment by fb55** [comment]
The implicit flag is added whenever a tag should be opened or closed (following the HTML spec), but isn't found in the input. Eg. a `<tr>` will implicitly open (create) a `<tbody>` tag.
