### ISSUE TITLE
WritableStream 'error' event not working

### ISSUE THREAD

**Issue by osddeitf** [fb55/htmlparser2#866]
For example, we have an implementation which may went wrong at `onopentag` callback due to programmer errors, which are common (e.g. could not access member of `undefined`). Below is just a demonstration:
```js
  return new Promise((resolve, reject) => {
    const document = new htmlparser2.Parser({
      onopentag: (name, attrs) => {
        throw new Error('reject at ' + name)
      }
      onend: () => {
        resolve(res)
      },
      onerror: (error) => {
        reject(error)
      }
    }, {
      xmlMode: true
    })

    try {
      const xml = fs.readFileSync('/some/file/path')

      document.write(xml as any)
      document.end()
    }
    catch (e) {
      reject(e)
    }
  })
```
The call to `document.write()` will throw, which is fine.
When we changed to using `WritableStream`, it is the same.

But, when we changed how we write to the parser:
```js
      const xml = fs.createReadStream('/some/file/path')
      xml.pipe(document).on('error', e => reject(e))
```
**The 'error' event is not handled, which causes the server (which calling this function) to crash immediately, NOT BECAUSE OF "Unhandled Promise Rejection"**.

I dug into it and find out in the implementation of `src/WritableStream.ts`:
```js
    _write(chunk: string | Buffer, encoding: string, cb: () => void): void {
        this._parser.write(
            isBuffer(chunk, encoding) ? this._decoder.write(chunk) : chunk
        );
        cb();
    }
```
`this._parser.write()` may throw an error, but the error is not passed to the callback, as [Nodejs documentation about implementing a writable stream](https://nodejs.org/dist/latest-v14.x/docs/api/stream.html#stream_writable_write_chunk_encoding_callback_1):

> The callback function must be called synchronously inside of writable._write() or asynchronously (i.e. different tick) to signal either that the write completed successfully or failed with an error. The first argument passed to the callback must be the Error object if the call failed or null if the write succeeded.

For stream event `error` to work, I have to change the implementation of `WritableStream` a bit:
```js
    _write(chunk: string | Buffer, encoding: string, cb: () => void): void {
        try {
          this._parser.write(
              isBuffer(chunk, encoding) ? this._decoder.write(chunk) : chunk
          );
          cb();
        }
        catch (e) {
          cb(e);
        }
    }
```

Environments:
- Nodejs: v14.16.1
- htmlparser2: v6.1.0

**Comment by fb55** [comment]
@osddeitf Thanks for the report! Could you share which error you have received? `this._parser.write()` should never throw an error. There is an `onerror` event that you can listen to, but the cases it covers (eg. writes after end) are eliminated by using Node.js streams.

**Comment by fb55** [comment]
Closing this for now. Please let me know if there is something to do here after all.
