### ISSUE TITLE
Add versioning notice to README

### ISSUE THREAD

**Issue by j-m** [fb55/htmlparser2#867]
Just a slight nitpick, could you add a description of your versioning notice/schema to the readme, please?

I came across: 

> Does htmlparser2 follow semver?  
Yes.
_Originally posted by @fb55 in https://github.com/fb55/htmlparser2/issues/161#issuecomment-161033152_

So I take it you're following semver, adding something as simple as a badge would be greatly appreciated, i.e.:

<a href="https://semver.org/"><img alt="semantic versioning" src="https://img.shields.io/static/v1?label=versioning&message=SemVer&color=informational"/></a>

`<a href="https://semver.org/"><img alt="semantic versioning" src="https://img.shields.io/static/v1?label=versioning&message=SemVer&color=informational"/></a>`

` [![semantic versioning](https://img.shields.io/static/v1?label=versioning&message=SemVer&color=informational)](https://semver.org/)`

(I was recently caught out by another project's README that said to install the package via `npm i ...` so I assumed that the package was following semver. Turns out they weren't and I unwittingly adopted a breaking change - the package should've said to use `npm i ... --save-exact`)

**Comment by fb55** [comment]
Hi @j-m, thanks for raising this! the general convention I've seen is that only libraries that don't follow semver have that explicitly in their READMEs. It is unfortunate that you experienced a package that didn't do that.

If there is more interest in adding an explicit badge, I'm happy to comply, but for now I will follow the lead of the majority of other packages. Hope that's alright!
