### ISSUE TITLE
Adding a line number parameter for callback functions

### ISSUE THREAD

**Issue by tkrugg** [fb55/htmlparser2#89]
It could be nice if say `.oncomment` would return the start-end line numbers.
I forked the project and added this feature for `.oncomment` but I'm considering extending it to other events.

**Comment by smmoosavi** [comment]
+1
Please provide line/col number.

**Comment by gabegorelick** [comment]
@smmoosavi htmlparser already supports everything you need to do this. Take a look at https://github.com/rubenv/angular-gettext-tools/commit/352e8d7cd1bbb9b1f51febe0416298662bb22ae7 for another example using [cheerio](https://github.com/cheeriojs/cheerio), which is provides a jQuery-like API on top of htmlparser2. Basically, all you need to do is pass `{withStartIndices: true}` and then count the number of newlines between the start of the HTML string and the node in question's index. 

But I suppose it'd be nice if htmlparser2 did the newline counting for you.

**Comment by smmoosavi** [comment]
Ok. Txn.

**Comment by tommck** [comment]
I would also love to see this support added.
If it's a perf issue, maybe it's a configurable option?

If someone has an implementation that works for them, please let me know.

Thanks

**Comment by ssivanatarajan** [comment]
Any update on this issue? @fb55

**Comment by tommck** [comment]
Considering he closed this issue 4 years ago... probably not :)
