### ISSUE TITLE
endIndex less than startIndex for implied tags

### ISSUE THREAD

**Issue by thewilkybarkid** [fb55/htmlparser2#896]
If I have

```ts
const p = new Parser({ onclosetag(name) {
  console.log({
    name,
    startIndex: p.startIndex,
    endIndex: p.endIndex,
  })
}})
```

and I run

```ts
p.write("<p>Foo</p><hr>");
```

I get

```ts
{ name: 'p', startIndex: 6, endIndex: 9 }
{ name: 'hr', startIndex: 10, endIndex: 13 }
```

But if I _don't_ include the optional end tag for the `<p>`:

```ts
p.write("<p>Foo<hr>");
```

I get

```ts

{ name: 'p', startIndex: 6, endIndex: 9 }
{ name: 'hr', startIndex: 10, endIndex: 9 }
```

The `endIndex` for the `hr` doesn't seem to have been set, so it's the same as for the `<p>`. This trips up PostHTML's `sourceLocations` option (https://github.com/posthtml/posthtml-parser/pull/63), which finds an `endIndex` less than a `startIndex`. This option is now used by Parcel, leading to https://github.com/parcel-bundler/parcel/issues/6672.

**Comment by thewilkybarkid** [comment]
Just seen the AST explorer (useful!), so put my case from https://github.com/parcel-bundler/parcel/issues/6672#issuecomment-892891275 at https://astexplorer.net/#/gist/a31bfb2e193e72e403256d885fd4b756/0153ebc4a547b3cbbf3003f033329740369e6aac (focusing on the `<hr>` shows the problem).

**Comment by thewilkybarkid** [comment]
After a bit of look, I think https://github.com/fb55/htmlparser2/blob/f38ddb86856d64b40184d23708dda53d77a3f7d6/src/Parser.ts#L263 and https://github.com/fb55/htmlparser2/blob/f38ddb86856d64b40184d23708dda53d77a3f7d6/src/Parser.ts#L233 are the problem lines: the inferred closing tag (i.e. the missing `</p>`) is given the indices of the new void element (`hr`), and as the `endIndex` is taken from the tokenizer directly (which has no knowledge of the inferred `</p>`) it's wrong.

I'm wondering though, what should the `startIndex`/`endIndex` be for the inferred `onclosetag` (if indeed that callback should be called at all)? Both `6` (so the beginning of the `<hr>`)? `6` and `9` (same as the `<hr>`? Maybe even both `null`?

**Comment by thewilkybarkid** [comment]
Seems like this happens on invalid HTML too: https://github.com/parcel-bundler/parcel/issues/6672#issuecomment-900395282.

**Comment by fb55** [comment]
@thewilkybarkid Thank you so much for the report, and for digging into the details! I have opened #910 with a refactor of start/end indices, which fixes this and other issues with how indices work.
