### ISSUE TITLE
startIndex not updated after a self-closing XML tag

### ISSUE THREAD

**Issue by thewilkybarkid** [fb55/htmlparser2#941]
After debugging https://github.com/parcel-bundler/parcel/pull/6752#issuecomment-908126589, the following XML:

```xml
<xml><a/><b/></xml>
```

gives the same `startIndex` on the`b` `openTag` event as it did for the `a` `openTag` (`5`, rather than the expected `9`).

**Comment by fb55** [comment]
Thanks for the report! Fixed this in #949 and released as `7.1.2`.
