### ISSUE TITLE
Can't recognize end tag correctly.

### ISSUE THREAD

**Issue by Edge00** [fb55/htmlparser2#962]
### Input
```html
<view>{{">_<"}}</view>
```

### Latest version
Got wrong text: '{{">_'

### v5.0.1
Got text '{{">_<"}}' correctly

### Reproduction link
https://astexplorer.net/

**Comment by fb55** [comment]
This should only be the case if you have `xmlMode` enabled. The behaviour was changed in https://github.com/fb55/htmlparser2/pull/778, explicitly for XML mode.
