### ISSUE TITLE
Some Boolean properties are indistinguishable from some plain empty string properties

### ISSUE THREAD

**Issue by jsonz1993** [fb55/htmlparser2#974]
[live demo](https://astexplorer.net/#/gist/2AmVrGuGVJ/0)

Some Boolean properties are indistinguishable from some plain empty string properties. 

Can there be some special marks or set a null to distinguish?

```html
<input disabled value="" />
```

![image](https://user-images.githubusercontent.com/11730463/136492028-318c1414-51bc-4803-a77d-6fa696b8b818.png)

**Comment by fb55** [comment]
You can get this information by hooking into the parser. The values are exposed on the `onattribute` events:

https://github.com/fb55/htmlparser2/blob/7ccc841062a666ba4547d0526071d636e3dff093/src/Parser.ts#L172-L182

`domhandler` will not add this information by default, but you can extend it to add these details to the DOM.
